---
title: "posterFigures"
output: html_document
date: "2026-04-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Prelims

```{r}
library(R.matlab)
library(mgcv)
addalpha <- function(col, alpha=.5){apply(sapply(col, col2rgb)/255, 2, function(x) rgb(x[1], x[2], x[3], alpha=alpha))}
```

## Load the Experiment 1 Data

```{r}
load("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Processed Data/AllElectrodes_Experiment1/allPallElectrodes.RData")
load("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Processed Data/AllElectrodes_Experiment1/plotAHead.RData")
load("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Processed Data/AllElectrodes_Experiment1/channelMapping.RData")
```

Calculate the median SNRs

```{r}
medianSNRCondition <- apply(avgSNRCondition, c(1,2,3), median, na.rm = TRUE)
medianScaled <- (medianSNRCondition - min(medianSNRCondition,na.rm = TRUE))/(max(medianSNRCondition,na.rm = TRUE)-min(medianSNRCondition,na.rm = TRUE))*(3.5-.5)+.5

dim(avgSNRCondition)
```

```{r}
posterColours <- c("#404040", "#F9F9F9", "#CC0033")
colourRampFunction <- colorRampPalette(posterColours, interpolate = "spline")
out <- hist(c(medianSNRCondition[,31,]), breaks = 10, plot = FALSE)
theColours <- colourRampFunction(length(out$mids))
colourMapping <- matrix(NA, nrow = dim(medianSNRCondition)[1], ncol = dim(medianSNRCondition)[3])
for (cond in 1:3){
  for (i in 1:length(out$mids)){
    colourMapping[medianSNRCondition[,31,cond] >= out$breaks[i] & medianSNRCondition[,31,cond] < out$breaks[i+1], cond] <- theColours[i]
  }
}

plot(x = NULL, y = NULL, ann = FALSE, axes = FALSE, xlim = c(0, length(out$mids)), ylim = c(0,.5))
for (i in 1:length(out$mids)){
  rect(i-1, 0, i, .5, col = theColours[i], border = theColours[i])
}
```

```{r, fig.width=10}
conditions <- c("Correlated Noise", "Anticorrelated Noise", "Control")

layout(matrix(c(1,2,3,4,4,4), nrow = 2, ncol = 3, byrow = TRUE), heights = c(.90, .1), widths = c(1,1,1))
par(pty = "s",  mai = c(.1,.1,.1,.1))
xLim <- range(pretty(range(electrodePositions[,1], headX, noseX, rightEarX, leftEarX)))
yLim <- range(pretty(range(electrodePositions[,2], headY, noseY, rightEarY, leftEarY)))
for (i in 1:3){
  plot(x = NULL, y = NULL, xlim = xLim, ylim = yLim, axes = FALSE, ann = FALSE)
  lines(headX, headY, col = "gray75", lwd = 2)
  lines(rightEarX, rightEarY, col = "gray75", lwd = 2)
  lines(leftEarX, leftEarY, col = "gray75", lwd = 2)
  lines(noseX, noseY, col = "gray75", lwd = 2)
  points(electrodePositions[,1], electrodePositions[,2], cex = medianScaled[channelmapping,31,i], pch = 21, col = colourMapping[channelmapping,i], bg = addalpha(colourMapping[channelmapping,i], .5), lwd = 1.5)
  
  mtext(conditions[i], 3, font = 2, adj = 0.5)
}

par(pty = "m",mai = c(0,0,.3,0))
plot(x = NULL, y = NULL, ann = FALSE, axes = FALSE, xlim = c(0, length(out$mids)), ylim = c(0,.5))
for (i in 1:length(out$mids)){
  rect(i-1, 0, i, .5, col = theColours[i], border = theColours[i])
}
mtext(sprintf("%.2f",out$breaks), 3, at = 0:length(out$mids))
mtext("Signal-to-Noise Ratio", 3, font = 2, line = 1.5, adj = 0, at = 0)
```

```{r}
eAveraged <- apply(avgSNRCondition[channelmapping[electrodeLayout %in% c("OZ","POZ", "O1","O2")],,,],c(2,3), median) 
eAveraged[1:9,] <- 1

eAvgCIS <- array(NA, dim = c(200,3,1000))
for (i in 1:1000){
  pIDX <- sample(1:15, 15, replace = TRUE)
  eAvgCIS[,,i] <- apply(avgSNRCondition[channelmapping[electrodeLayout %in% c("OZ","POZ", "O1","O2")],,,pIDX],c(2,3), median)
}

eAvgCI <-  apply(eAvgCIS,c(1,2), quantile, probs = c(.025,.975), na.rm = TRUE) 
eAvgCI[,1:9,] <- 1
```

```{r, fig.width=12}
png("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Figures/HeadPlotsExp1.png", width = 12, height = 6, res = 300,units = "in", bg = "transparent")
x <- electrodePositions[,1]
y <- electrodePositions[,2]

dataTemp <- expand.grid(seq(-.6, .6,.001),seq(yLim[1],yLim[2],.001))
dataToInterp <- data.frame(X = dataTemp[,1], Y = dataTemp[,2])
dataTemp$Z <- rep(1,length(dataTemp[,1]))
catGrid <- pracma::cart2pol(as.matrix(dataTemp))
Rmap <- catGrid[, "r"]

layout(matrix(c(1,2,3,4,5,6,7,8), nrow = 2, ncol = 4, byrow = TRUE), heights = c(.5, .5), widths = c(.3,.3,.3,.1))
par(pty = "s",  mai = c(.1,.1,.1,.1), omi = c(.3,.5,.1,0))
for (C in 1:3){
  Z <- medianSNRCondition[channelmapping,31,C]
  dataToFit <- data.frame(Z = Z, X = x, Y = y)
  model <- gam(Z ~ s(X, Y, bs = "ts", k = 40), data = dataToFit)
  Zp <- predict.gam(model, newdata = dataToInterp)
  
  Zp[Rmap > .5] <- NA
  
  theColours <- colourRampFunction(length(out$mids))
  par(pty = "s")
  image(x = seq(-.6,.6,.001), 
        y = seq(-.6,.6,.001), 
        z = matrix(Zp, nrow = length(seq(-.6,.6,.001)), byrow = FALSE), 
        col = theColours, 
        breaks = out$breaks, axes = FALSE, ann = FALSE)
  lines(headX, headY, col = "gray75", lwd = 2)
  lines(rightEarX, rightEarY, col = "gray75", lwd = 2)
  lines(leftEarX, leftEarY, col = "gray75", lwd = 2)
  lines(noseX, noseY, col = "gray75", lwd = 2)
  points(x,y, pch = 21, col = NA, bg = rgb(.75,.75,.75,.5))
  mtext(conditions[C], 3, font = 2, adj = 0.5)
}

par(pty = "m",mai = c(0,0.1,0,.5))
plot(x = NULL, y = NULL, ann = FALSE, axes = FALSE, ylim = c(0, length(out$mids)), xlim = c(0,.5))
for (i in 1:length(out$mids)){
  rect(0,i-1, .5, i, col = theColours[i], border = theColours[i])
}

mtext(sprintf("%.2f",pretty(out$breaks)), 4, at = seq(0, length(out$mids), length.out = length(pretty(out$breaks))), las = 1)
mtext("Signal-to-Noise Ratio", 2, font = 2, line = .5, adj = 1, at = length(out$mids))

xLimit <- c(1,200)
yLimit <- range(pretty(range(pretty(range(eAveraged)))))

for (i in 1:3){
  par(mai = c(.1,.1,.1,.1))
  plot(x = NULL, y = NULL, xlim = xLimit, ylim = yLimit, axes = FALSE, ann = FALSE)
  axis(2, at = pretty(yLimit), lwd = 2, tck = -.015, labels = FALSE)
  mtext(c(0,3,6,9,12,15,18,20), 1, at = c(0,31,61,91,121,151,181,200), line = .5)
  if (i == 1){
    mtext("SNR", 2, font = 2, line = 3)
    mtext(sprintf("%.2f",pretty(yLimit)), 2, at = pretty(yLimit), line = .4, las = 1)
  }
  
  abline(v = c(31,61,91,121,151,181), lty = 2, lwd = 2, col = "gray85")
  axis(1, at = c(0,31,61,91,121,151,181,200), tck = -.015, labels = FALSE, lwd = 2)
  mtext("Frequency (Hz)", 1, font = 2, line = 1.75)
  
  polygon(c(1:200, 200:1), c(eAvgCI[1,,i], rev(eAvgCI[2,,i])), col = addalpha(theColours[1],.5), border = FALSE)
  lines(1:200,eAveraged[,i], lwd = 4, col = theColours[3])
}
dev.off()
```

Exp 1 - Behaviour

```{r}
# Remove 5 and 6 for correlation analysis
theCompleteParticipants <- c("001", "002", "003", "004", "007", "008", "009", "010", "011", "012", "013", "014", "015")
behaviourDatadir <- paste0("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Behaviour Data/")

correct <- NULL
levels <- NULL
reversals <- NULL

threshold <- matrix(NA, nrow = 6, ncol = length(theCompleteParticipants))

for (p in 1:length(theCompleteParticipants)){
  dataTemp <- readMat(paste0(behaviourDatadir,theCompleteParticipants[p],'/',paste0(theCompleteParticipants[p], "Final.mat")))
  
  correct <- NULL
  levels <- NULL
  reversals <- NULL
  block <- NULL
  
  for (i in 1:6){
    correct <- c(correct, dataTemp$Exp[,,1]$Staircase[,,i]$response)
    levels <- c(levels, round(dataTemp$Exp[,,1]$Staircase[,,i]$x,2))
    reversals <- c(reversals, dataTemp$Exp[,,1]$Staircase[,,i]$reversal)
    block <- c(block, rep(i, length(dataTemp$Exp[,,1]$Staircase[,,i]$reversal)))
  }
  
  theVariableName <- paste0("allStaircases", p)
  assign(theVariableName, data.frame(participant=theCompleteParticipants[p], block = block, correct = correct, levels = levels, reversals = reversals))
  
  threshold[,p] <- dataTemp$Exp[,,1]$MeanReversalThreshold
}

allStaircases <- rbind(allStaircases1, allStaircases2,allStaircases3,allStaircases4,allStaircases5,allStaircases6,allStaircases7,allStaircases8,allStaircases9,allStaircases10,allStaircases11,allStaircases12,allStaircases13)
remove(allStaircases1,allStaircases2,allStaircases3,allStaircases4,allStaircases5,allStaircases6,allStaircases7,allStaircases8,allStaircases9,allStaircases10,allStaircases11,allStaircases12,allStaircases13)
```

```{r}
pixperdeg <- 36.7325
allStaircases$arcsec <- (allStaircases$levels*2)/pixperdeg*60*60

psychometricData <- aggregate(correct ~ levels + participant, data = allStaircases, FUN = base::mean)
psychometricData.SD <- aggregate(correct ~ levels + participant, data = allStaircases, FUN = stats::sd)
staircaseThresholds <- aggregate(arcsec ~ participant, data = allStaircases, FUN = pracma::geomean, subset = reversals %in% c(12,11,10,9,8))
```

```{r}
fitCumGauss <- function(params,X, data){
  mean <- params[1]
  sd <- params[2]
  gamma <- .5 #Guess Rate
  lambda <- params[3] #Lapse Rate
  
  YY <- gamma + (1 - gamma - lambda)*.5*pracma::erfc(-sd*(X-mean)/sqrt(2))
  err <- sum((YY - data)**2)
  return(err)
}

cumGauss <- function(params, X){
  mean <- params[1]
  sd <- params[2]
  gamma <- .5 #Guess Rate
  lambda <- .001 #Lapse Rate
  
  YY <- gamma + (1 - gamma - lambda)*.5*pracma::erfc(-sd*(X-mean)/sqrt(2))
  return(YY)
}

fitGumbell <- function(params, X, data){
  alpha <- params[1]
  beta <- params[2]
  gamma <- .5 #Guess Rate
  lambda <- params[3] #Lapse Rate
  
  YY <- gamma + (1 - gamma - lambda)*(1-exp(-1*10**(beta*(X-alpha))))
  err <- sum((YY - data)**2)
  return(err)
}

gumBell <- function(params, X){
  alpha <- params[1]
  beta <- params[2]
  gamma <- .5 #Guess Rate
  lambda <- params[3] #Lapse Rate
  
  YY <- gamma + (1 - gamma - lambda)*(1-exp(-1*10**(beta*(X-alpha))))
  return(YY)
}
```

```{r, fig.width=12, fig.height=6}
png("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Figures/participantThresholdsStereo.png", width = 12 , height = 7, res = 300, units = "in", bg = "transparent")
pixperdeg <- 36.7325
psychometricData$arcsec <- (psychometricData$levels*2)/pixperdeg*60*60
psychometricDataSD <- aggregate(correct ~ levels + participant, data = allStaircases, FUN = stats::sd)
psychometricData$minMax <- 1+(3-1)*(psychometricDataSD$correct-min(psychometricDataSD$correct, na.rm = TRUE))/(max(psychometricDataSD$correct,na.rm = TRUE)-min(psychometricDataSD$correct,na.rm = TRUE))
parti <- unique(psychometricData$participant)

par(mfrow = c(3,5), mai = c(.1,.1,.1,.1), omi = c(.3,.5,0,0), pty = "s")
threshold <- NULL
nSamples <- 1000
threshold.CI <- matrix(NA, nrow = nSamples, ncol = length(parti))
for (i in 1:length(parti)){
  dataSub <- psychometricData[psychometricData$participant == parti[i], ]
  theParams <- c(25,.1,.001)
  theParamsBest <- optim(theParams,fn = fitCumGauss, X = dataSub$arcsec, data = dataSub$correct)
  threshold[i] <- theParamsBest$par[1]
  
  for (ii in 1:nSamples){
    rowIDX <- sample(1:dim(dataSub)[1],dim(dataSub)[1], replace = TRUE)
    sampledData <- dataSub[rowIDX,]
    theParamsBest.CI <- optim(theParams,fn = fitCumGauss, X = sampledData$arcsec, data = sampledData$correct)
    threshold.CI[ii,i] <- theParamsBest.CI$par[1]
  }
  
  XX <- seq(min(dataSub$arcsec), max(dataSub$arcsec), .01)
  YY <- cumGauss(theParamsBest$par, XX)
  YY.CI.Low <- cumGauss(c(quantile(threshold.CI[,i],.025), theParamsBest$par[c(2,3)]), XX)
  YY.CI.High <- cumGauss(c(quantile(threshold.CI[,i],.975), theParamsBest$par[c(2,3)]), XX)
  
  xLimit <- range(pretty(range(psychometricData$arcsec)))
  yLimit <- c(0.5, 1)
  
  plot(x = NULL, y = NULL, xlim = xLimit,ylim = yLimit, axes = FALSE, ann = FALSE)
  axis(1, at = pretty(xLimit), tck = -0.015, lwd = 2, labels = FALSE)
  axis(2, at = pretty(yLimit), tck = -0.015, lwd = 2, labels = FALSE)
  if (i >= 9){
    mtext(pretty(xLimit), 1, at = pretty(xLimit), line = .4)
    mtext("Total Disparity (arcsec)", 1, font = 2, line = 1.5)
  }
  if (i %% 5 == 1){
    mtext(pretty(yLimit), 2, at = pretty(yLimit), line = .4, las = 1)
    mtext("Proportion Correct", 2, font = 2, line = 2.25)
  }
  
  polygon(c(XX, rev(XX)), c(YY.CI.Low, rev(YY.CI.High)), border = NA, col = "gray75")
  lines(XX, YY, lwd = 4, col = theColours[4])
  points(dataSub$arcsec, dataSub$correct, cex = 1+dataSub$minMax, pch = 21, bg = theColours[4], col = "white", lwd = 1.5)
  points(threshold[i], .5, pch = 25, col = "black", bg = "black", cex = 1.2)
  legend("bottomright", legend = paste0("P", theCompleteParticipants[i]), bty = "n")
}

pThreshold.CI <- apply(threshold.CI, 2, quantile, c(.025, .975))
dev.off()
```

```{r}
eAvgParticipant <- apply(avgSNRCondition[channelmapping[electrodeLayout %in% c("OZ","POZ", "O1","O2")],,,],c(2,3,4), median)
theCorrData <- eAvgParticipant[31, , c(1:4,7:15)]

theElectrodeCI <- array(NA, dim = c(3,13,nSamples))
for (i in 1:nSamples){
  IDX <- sample(c("OZ","POZ", "O1","O2"), 4, replace = TRUE)
  rowIndex <- channelmapping[electrodeLayout %in% IDX]
  if (length(rowIndex) < 4){
    rowIndex <- rep(rowIndex,length.out = 4)
  }
  eAvgParticipant.CI <- apply(avgSNRCondition[rowIndex,,,],c(2,3,4), median)
  theElectrodeCI[,,i] <- eAvgParticipant.CI[31,,c(1:4,7:15)]
}

theElectrodeCI.P <- apply(theElectrodeCI, c(1,2), quantile, c(0.025, .975))
```


```{r, fig.width=10}
png("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Figures/corMatrix.png", width = 7, height = 6, res = 300, units = "in", bg = "transparent")

theM <- cor(cbind(t(theCorrData),threshold))
colnames(theM) <- c("Correlated Noise", "Anticorrelated Noise", "Control", "Stereoacuity")
rownames(theM) <- c("Correlated Noise", "Anticorrelated Noise", "Control", "Stereoacuity")

layout(matrix(c(1,2), nrow = 1, ncol = 2),widths = c(.9,.1), heights = 1)
par(pty = "s", mai = c(0,1.5,1.7,0))
theMColours <- colourRampFunction(100)
image(1:4, 1:4, matlab::rot90(theM,3), col = theMColours, zlim = c(-1,1), axes = FALSE, ann = FALSE)
mtext(c("Correlated Noise", "Anticorrelated Noise", "Control", "Stereoacuity"), 2, at = 4:1, las = 1, font = 2)
mtext(c("Correlated Noise", "Anticorrelated Noise", "Control", "Stereoacuity"), 3, at = 1:4, las = 2, font = 2)

par(pty = "m", mai = c(0,0,1.7, .3))
plot(x = NULL, y = NULL, xlim = c(0,1), ylim = c(0, length(theMColours)), axes = FALSE, ann = FALSE)
for (i in 1:length(theMColours)){
  rect(0, i-1, 1, i, col = theMColours[i], border = theMColours[i ])
}
mtext(pretty(c(-1,1)), 4, at = seq(0,length(theMColours), length.out = length(pretty(c(-1,1)))), las = 1)
mtext("Correlation Coefficient", 2, font = 2, at = length(theMColours), adj = 1)
dev.off()
```

```{r}
png("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Figures/correlations.png", width = 8, height = 4, res = 300, units = "in", bg = "transparent")
par(mfrow = c(1,3), mai = c(.3,.3,.1,0), omi = c(.3,.5,.1,.1), pty = "s")
yLimit <- range(pretty(range(theElectrodeCI.P)))
xLimit <- c(0,max(pretty(range(pretty(range(pThreshold.CI))))))

plot(x = NULL, y = NULL, xlim = xLimit, ylim = yLimit, axes = FALSE, ann = FALSE)
abline(lm(theCorrData[1,]~threshold), lwd = 3, col = theColours[2])
arrows(pThreshold.CI[1,], theCorrData[1,], pThreshold.CI[2,], theCorrData[1,], length = .015, angle = 90, code = 3, col = theColours[4], lwd = 2)
arrows(threshold, theElectrodeCI.P[1,1,], threshold, theElectrodeCI.P[2,1,], length = .015, angle = 90, code = 3, col = theColours[4], lwd = 2)
points(threshold, theCorrData[1,],bg = theColours[4], pch = 21, cex = 2, col = "white")

axis(1, at = pretty(xLimit), lwd = 2, tck = -.015, labels = FALSE)
axis(2, at = pretty(yLimit), lwd = 2, tck = -.015, labels = FALSE)
mtext(pretty(xLimit), 1, at = pretty(xLimit), line=.4, las = 1)
mtext(pretty(yLimit),2, at = pretty(yLimit), line = .4, las = 1)

legend("bottomright", legend = paste0("r = ", round(theM[1,4],3)), bty = "n", cex = 1.2)

mtext("Total Disparity (arcsec)", 1, font = 2, line = 1.75)
mtext("Signal-to-Noise Ratio", 2, font = 2, line = 1.75)
mtext("Correlated Noise", 3, font = 2, adj = 0.5)

plot(x = NULL, y = NULL, xlim = xLimit, ylim = yLimit, axes = FALSE, ann = FALSE)
abline(lm(theCorrData[2,]~threshold), lwd = 3, col = theColours[2])
arrows(pThreshold.CI[1,], theCorrData[2,], pThreshold.CI[2,], theCorrData[2,], length = .015, angle = 90, code = 3, col = theColours[4], lwd = 2)
arrows(threshold, theElectrodeCI.P[1,2,], threshold, theElectrodeCI.P[2,2,], length = .015, angle = 90, code = 3, col = theColours[4], lwd = 2)

points(threshold,theCorrData[2,], bg = theColours[4], pch = 21, cex = 2, col = "white")
axis(1, at = pretty(xLimit), lwd = 2, tck = -.015, labels = FALSE)
axis(2, at = pretty(yLimit), lwd = 2, tck = -.015, labels = FALSE)
mtext(pretty(xLimit),1, at = pretty(xLimit), line = .4)
mtext("Total Disparity (arcsec)", 1, font = 2, line = 1.75)
mtext("Anticorrelated Noise", 3, font = 2, adj = 0.5)
legend("bottomright", legend = paste0("r = ", round(theM[2,4],3)), bty = "n", cex = 1.2)


plot(x = NULL, y = NULL, xlim = xLimit, ylim = yLimit, axes = FALSE, ann = FALSE)
abline(lm(theCorrData[3,]~threshold), lwd = 3, col = theColours[2])
arrows(pThreshold.CI[1,], theCorrData[3,], pThreshold.CI[2,], theCorrData[3,], length = .015, angle = 90, code = 3, col = theColours[4], lwd = 2)
arrows(threshold, theElectrodeCI.P[1,3,], threshold, theElectrodeCI.P[2,3,], length = .015, angle = 90, code = 3, col = theColours[4], lwd = 2)

points(threshold,theCorrData[3,], bg = theColours[4], pch = 21, cex = 2, col = "white")
axis(1, at = pretty(xLimit), lwd = 2, tck = -.015, labels = FALSE)
axis(2, at = pretty(yLimit), lwd = 2, tck = -.015, labels = FALSE)
mtext(pretty(xLimit),1, at = pretty(xLimit), line = .4)
mtext("Total Disparity (arcsec)", 1, font = 2, line = 1.75)
mtext("Control", 3, font = 2, adj = 0.5)
legend("bottomright", legend = paste0("r = ", round(theM[3,4],3)), bty = "n", cex = 1.2)
dev.off()
```


```{r}
xLimit <- range(pretty(range(psychometricDataAvg$arcsec)))
yLimit <- c(0.5, 1)

plot(x = NULL, y = NULL, xlim = xLimit,ylim = yLimit, axes = FALSE, ann = FALSE)
axis(1, at = pretty(xLimit), tck = -0.015, lwd = 2, labels = FALSE)
axis(2, at = pretty(yLimit), tck = -0.015, lwd = 2, labels = FALSE)
mtext(pretty(xLimit), 1, at = pretty(xLimit), line = .4)
mtext(pretty(yLimit), 2, at = pretty(yLimit), line = .4, las = 1)
mtext("Proportion Correct", 2, font = 2, line = 2)

points(psychometricDataAvg$arcsec, psychometricDataAvg$correct, cex = 1+psychometricDataSD$minMax, pch = 21, bg = theColours[4], col = "white", lwd = 1.5)
lines(XX, YY, lwd = 3, col = theColours[3])
```



```{r}
load("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Processed Data/AllElectrodes_Experiment2/allPallElectrodes.RData")
```


```{r}
out <- hist(c(medianSNRCondition[,31,]), breaks = 10, plot = FALSE)
theColours <- colourRampFunction(length(out$mids))
colourMapping <- matrix(NA, nrow = dim(medianSNRCondition)[1], ncol = dim(medianSNRCondition)[3])
for (cond in 1:dim(medianSNRCondition)[3]){
  for (i in 1:length(out$mids)){
    colourMapping[medianSNRCondition[,31,cond] >= out$breaks[i] & medianSNRCondition[,31,cond] < out$breaks[i+1], cond] <- theColours[i]
  }
}
```

```{r, fig.width=15}
conditions <- c("Correlated Noise", "Anticorrelated Noise")
corCond <- c(0,0.12, 0.24, 0.48, 0.96)
layout(matrix(c(1,2,3,4,5,6,7,8,9,10,11,11,11,11,11), nrow = 3, ncol = 5, byrow = TRUE), heights = c(.45,.45, .1), widths = c(1,1,1))
par(pty = "s", mai = c(.1,.1,.1,.1), omi = c(.1,.1,.1,.1))
xLim <- range(pretty(range(electrodePositions[,1], headX, noseX, rightEarX, leftEarX)))
yLim <- range(pretty(range(electrodePositions[,2], headY, noseY, rightEarY, leftEarY)))
counter <- 0
for (i in 1:10){
  plot(x = NULL, y = NULL, xlim = xLim, ylim = yLim, axes = FALSE, ann = FALSE)
  lines(headX, headY, col = "gray75", lwd = 2)
  lines(rightEarX, rightEarY, col = "gray75", lwd = 2)
  lines(leftEarX, leftEarY, col = "gray75", lwd = 2)
  lines(noseX, noseY, col = "gray75", lwd = 2)
  points(electrodePositions[,1], electrodePositions[,2], cex = medianScaled[channelmapping,31,i], pch = 21, col = colourMapping[channelmapping,i], bg = addalpha(colourMapping[channelmapping,i], .5), lwd = 1.5)
  
  if (i == 3 | i == 8){
    counter <- counter+1
    mtext(conditions[counter], 3, font = 2, adj = 0.5, cex = 1.5, line = 2)
  }
  if (i == 1 | i == 6){
    mtext("Interocular Correlation", 1, line = -1, adj = 0, font = 1, cex = 1.2)
  }
  mtext(corCond[c((i-1) %% 5)+1], 1, line = 1.5, cex = 1.1)
}

par(pty = "m", mai = c(0,0,.6,0))
plot(x = NULL, y = NULL, ann = FALSE, axes = FALSE, xlim = c(0, length(out$mids)), ylim = c(0,.5))
for (i in 1:length(out$mids)){
  rect(i-1, 0, i, .5, col = theColours[i], border = theColours[i])
}
mtext(sprintf("%.2f",out$breaks), 3, at = 0:length(out$mids))
mtext("Signal-to-Noise Ratio", 3, font = 2, line = 1.5, adj = 0, at = 0)
```