---
title: "posterFiguresExp2"
output: html_document
date: "2026-04-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Prelims

```{r}
library(R.matlab)
library(mgcv)
addalpha <- function(col, alpha=.5){apply(sapply(col, col2rgb)/255, 2, function(x) rgb(x[1], x[2], x[3], alpha=alpha))}
```


```{r}
load("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Processed Data/AllElectrodes_Experiment2/allPallElectrodes.RData")
load("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Processed Data/AllElectrodes_Experiment1/plotAHead.RData")
load("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Processed Data/AllElectrodes_Experiment1/channelMapping.RData")
```

```{r}
nSamples <- 1000
medianSNRCondition <- apply(avgSNRCondition, c(1,2,3), median, na.rm = TRUE)
medianScaled <- (medianSNRCondition - min(medianSNRCondition,na.rm = TRUE))/(max(medianSNRCondition,na.rm = TRUE)-min(medianSNRCondition,na.rm = TRUE))*(3.5-.5)+.5

dim(avgSNRCondition)
```

```{r}
posterColours <- c("#404040", "#F9F9F9", "#CC0033")
colourRampFunction <- colorRampPalette(posterColours, interpolate = "spline")
out <- hist(c(medianSNRCondition[,31,]), breaks = 10, plot = FALSE)
theColours <- colourRampFunction(length(out$mids))
colourMapping <- matrix(NA, nrow = dim(medianSNRCondition)[1], ncol = dim(medianSNRCondition)[3])
for (cond in 1:3){
  for (i in 1:length(out$mids)){
    colourMapping[medianSNRCondition[,31,cond] >= out$breaks[i] & medianSNRCondition[,31,cond] < out$breaks[i+1], cond] <- theColours[i]
  }
}

plot(x = NULL, y = NULL, ann = FALSE, axes = FALSE, xlim = c(0, length(out$mids)), ylim = c(0,.5))
for (i in 1:length(out$mids)){
  rect(i-1, 0, i, .5, col = theColours[i], border = theColours[i])
}

completePosterColours <- colourRampFunction(10)
```

```{r}
out <- hist(c(medianSNRCondition[,31,]), breaks = 10, plot = FALSE)
breaksTemp <- seq(.7, 1.3, .05)
midsTemp <- breaksTemp[1:(length(breaksTemp)-1)]+diff(breaksTemp)/2
theColours <- colourRampFunction(length(out$mids))
colourMapping <- matrix(NA, nrow = dim(medianSNRCondition)[1], ncol = dim(medianSNRCondition)[3])
for (cond in 1:dim(medianSNRCondition)[3]){
  for (i in 1:length(midsTemp)){
    colourMapping[medianSNRCondition[,31,cond] >= breaksTemp[i] & medianSNRCondition[,31,cond] < breaksTemp[i+1], cond] <- theColours[i]
  }
}
```

```{r, fig.width=15}
conditions <- c("Correlated Noise", "Anticorrelated Noise")
corCond <- c(0,0.12, 0.24, 0.48, 0.96)
layout(matrix(c(1,2,3,4,5,6,7,8,9,10,11,11,11,11,11), nrow = 3, ncol = 5, byrow = TRUE), heights = c(.45,.45, .1), widths = c(1,1,1))
par(pty = "s", mai = c(.1,.1,.1,.1), omi = c(.1,.1,.1,.1))
xLim <- range(pretty(range(electrodePositions[,1], headX, noseX, rightEarX, leftEarX)))
yLim <- range(pretty(range(electrodePositions[,2], headY, noseY, rightEarY, leftEarY)))
counter <- 0
for (i in 1:10){
  plot(x = NULL, y = NULL, xlim = xLim, ylim = yLim, axes = FALSE, ann = FALSE)
  lines(headX, headY, col = "gray75", lwd = 2)
  lines(rightEarX, rightEarY, col = "gray75", lwd = 2)
  lines(leftEarX, leftEarY, col = "gray75", lwd = 2)
  lines(noseX, noseY, col = "gray75", lwd = 2)
  points(electrodePositions[,1], electrodePositions[,2], cex = medianScaled[channelmapping,31,i], pch = 21, col = colourMapping[channelmapping,i], bg = addalpha(colourMapping[channelmapping,i], .5), lwd = 1.5)
  
  if (i == 3 | i == 8){
    counter <- counter+1
    mtext(conditions[counter], 3, font = 2, adj = 0.5, cex = 1.5, line = 0)
  }
  if (i == 1 | i == 6){
    mtext("Interocular\nCorrelation", 1, line = 0, adj = 0.5, font = 1, cex = 1.2, padj = .5, at = -.5)
  }
  mtext(corCond[c((i-1) %% 5)+1], 1, line = 0, cex = 1.1)
}

par(pty = "m", mai = c(0,0,.6,0))
plot(x = NULL, y = NULL, ann = FALSE, axes = FALSE, xlim = c(0, length(out$mids)), ylim = c(0,.5))
for (i in 1:length(out$mids)){
  rect(i-1, 0, i, .5, col = theColours[i], border = theColours[i])
}
mtext(sprintf("%.2f",out$breaks), 3, at = 0:length(out$mids))
mtext("Signal-to-Noise Ratio", 3, font = 2, line = 1.5, adj = 0, at = 0)
```

```{r}
eAveraged <- apply(avgSNRCondition[channelmapping[electrodeLayout %in% c("OZ","POZ", "O1","O2")],,,],c(2,3,4), median) 
pAveraged <- apply(eAveraged,c(1,2), median) 

eAveraged[1:9,,] <- 1
pAveraged[1:9,] <- 1

theSNRCIData <- avgSNRCondition[channelmapping[electrodeLayout %in% c("OZ","POZ", "O1","O2")],31,,]

theElectrodeCI <- array(NA, dim = c(15,48,nSamples))
pAvgCITemp <- array(NA, dim = c(200,15,nSamples))
for (i in 1:nSamples){
  IDX <- sample(1:4, 4, replace = TRUE)
  theElectrodeCI[,,i] <- apply(theSNRCIData[IDX,,],c(2,3), median)
  
  pIDX <- sample(1:dim(eAveraged)[3], dim(eAveraged)[3], replace = TRUE)
  pAvgCITemp[,,i] <- apply(eAveraged[,,pIDX],c(1,2), median) 
}

pAvgCI <- apply(pAvgCITemp, c(1,2), quantile,c(0.025, .975))
theElectrodeCI.P <- apply(theElectrodeCI, c(1,2), quantile, c(0.025, .975))

dim(pAvgCI)
```


```{r, fig.width=20}
png("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Figures/HeadPlotsExp2.png", width = 20, height = 12, res = 300, units = "in", bg = "transparent")
x <- electrodePositions[,1]
y <- electrodePositions[,2]

dataTemp <- expand.grid(seq(-.6, .6,.001),seq(-.6,.6,.001))
dataToInterp <- data.frame(X = dataTemp[,1], Y = dataTemp[,2])
dataTemp$Z <- rep(1,length(dataTemp[,1]))
catGrid <- pracma::cart2pol(as.matrix(dataTemp))
Rmap <- catGrid[, "r"]

eegMatrix<- matrix(1:20, nrow = 4, ncol =5, byrow = TRUE)
colourbar <- c(21,23,22,24)
finalMatrix <- cbind(eegMatrix,colourbar)
layout(finalMatrix, heights = c(.3,.2,.3,.2), widths = c(.2,.2,.2,.2,.2,.1))

par(pty = "s",  mai = c(0,.1,.5,.1), omi = c(.1,.1,.1,.1))
counter <- 0

# Segment 1: 0.5 to 1.0 (5 points)
# Uses p = 1.5 for a slight deceleration into the midpoint
x_lower <- seq(0, 1, length.out = 10)
y_lower <- 0.7 + (1.0 - 0.7) * (x_lower ^ 1.5)

# Segment 2: 1.0 to 3.0 (5 points, then remove the first to avoid duplicating 1.0)
# Uses p = 0.7 to compress the larger range (1.0-3.0) for visual balance
x_upper <- seq(0, 1, length.out = 10)
y_upper <- 1.0 + (1.3 - 1.0) * (x_upper ^ 0.7)

# Combine segments (removing the first element of y_upper to keep it at 9 numbers)
breaksTemp <- c(y_lower, y_upper[-1])
midsTemp <- breaksTemp[1:(length(breaksTemp)-1)] + diff(breaksTemp)/2
theColours <- colourRampFunction(length(midsTemp))

for (C in 1:5){
  Z <- medianSNRCondition[channelmapping,31,C]
  dataToFit <- data.frame(Z = Z, X = x, Y = y)
  model <- gam(Z ~ s(X, Y, bs = "ts", k = 40), data = dataToFit)
  Zp <- predict.gam(model, newdata = dataToInterp)
  
  Zp[Rmap > .5] <- NA
  par(pty = "s")
  image(x = seq(-.6,.6,.001), 
        y = seq(-.6,.6,.001), 
        z = matrix(Zp, nrow = length(seq(-.6,.6,.001)), byrow = FALSE), 
        col = theColours, 
        breaks = breaksTemp, axes = FALSE, ann = FALSE)
  lines(headX, headY, col = "gray75", lwd = 2)
  lines(rightEarX, rightEarY, col = "gray75", lwd = 2)
  lines(leftEarX, leftEarY, col = "gray75", lwd = 2)
  lines(noseX, noseY, col = "gray75", lwd = 2)
  points(x,y, pch = 21, col = NA, bg = rgb(.75,.75,.75,.5))
  
  
  if (C == 3 | C == 8){
    counter <- counter+1
    mtext(conditions[counter], 3, font = 2, adj = 0.5, cex = 1.5, line = 2)
  }
  if (C == 1 | C == 6){
    mtext("Interocular\nCorrelation", 3, line = 0, adj = 0.5, font = 1, cex = 1.2, padj = .5, at = -.4)
  }
  mtext(corCond[(C-1)%%5+1%%5], 3, line = 0, cex = 1.1)
}


par(pty = "m",  mai = c(.5,.5,0,.1))

xLimit <- c(1,200)
yLimit <- c(.5,2)

for (i in 1:5){
  plot(x = NULL, y = NULL, xlim = xLimit, ylim = yLimit, axes = FALSE, ann = FALSE)
  axis(2, at = pretty(yLimit), lwd = 2, tck = -.015, labels = FALSE)
  mtext(c(0,3,6,9,12,15,18,20), 1, at = c(0,31,61,91,121,151,181,200), line = .5)
  if (i == 1 | i == 6){
    mtext("SNR", 2, font = 2, line = 3)
    mtext(sprintf("%.1f",pretty(yLimit)), 2, at = pretty(yLimit), line = .4, las = 1)
  }
  
  abline(v = c(31,61,91,121,151,181), lty = 2, lwd = 2, col = "gray85")
  axis(1, at = c(0,31,61,91,121,151,181,200), tck = -.015, labels = FALSE, lwd = 2)
  mtext("Frequency (Hz)", 1, font = 2, line = 1.75)
  
  polygon(c(1:200, 200:1), c(pAvgCI[1,,i], rev(pAvgCI[2,,i])), col = addalpha(completePosterColours[1],.5), border = FALSE)
  lines(1:200,pAveraged[,i], lwd = 4, col = completePosterColours[3])
}

par(pty = "s", mai = c(0,.1,.5,.1))

for (C in 6:10){
  Z <- medianSNRCondition[channelmapping,31,C]
  dataToFit <- data.frame(Z = Z, X = x, Y = y)
  model <- gam(Z ~ s(X, Y, bs = "ts", k = 40), data = dataToFit)
  Zp <- predict.gam(model, newdata = dataToInterp)
  
  Zp[Rmap > .5] <- NA
  par(pty = "s")
  image(x = seq(-.6,.6,.001), 
        y = seq(-.6,.6,.001), 
        z = matrix(Zp, nrow = length(seq(-.6,.6,.001)), byrow = FALSE), 
        col = theColours, 
        breaks = breaksTemp, axes = FALSE, ann = FALSE)
  lines(headX, headY, col = "gray75", lwd = 2)
  lines(rightEarX, rightEarY, col = "gray75", lwd = 2)
  lines(leftEarX, leftEarY, col = "gray75", lwd = 2)
  lines(noseX, noseY, col = "gray75", lwd = 2)
  points(x,y, pch = 21, col = NA, bg = rgb(.75,.75,.75,.5))
  
  
  if (C == 3 | C == 8){
    counter <- counter+1
    mtext(conditions[counter], 3, font = 2, adj = 0.5, cex = 1.5, line = 2)
  }
  if (C == 1 | C == 6){
    mtext("Interocular\nCorrelation", 3, line = 0, adj = 0.5, font = 1, cex = 1.2, padj = .5, at = -.4)
  }
  mtext(paste0("-",corCond[(C-1)%%5+1%%5]), 3, line = 0, cex = 1.1)
}

par(pty = "m",  mai = c(.5,.5,0,.1))
xLimit <- c(1,200)
yLimit <- c(.5,2)

for (i in 6:10){
  plot(x = NULL, y = NULL, xlim = xLimit, ylim = yLimit, axes = FALSE, ann = FALSE)
  axis(2, at = pretty(yLimit), lwd = 2, tck = -.015, labels = FALSE)
  mtext(c(0,3,6,9,12,15,18,20), 1, at = c(0,31,61,91,121,151,181,200), line = .5)
  if (i == 1 | i == 6){
    mtext("SNR", 2, font = 2, line = 3)
    mtext(sprintf("%.1f",pretty(yLimit)), 2, at = pretty(yLimit), line = .4, las = 1)
  }
  
  abline(v = c(31,61,91,121,151,181), lty = 2, lwd = 2, col = "gray85")
  axis(1, at = c(0,31,61,91,121,151,181,200), tck = -.015, labels = FALSE, lwd = 2)
  mtext("Frequency (Hz)", 1, font = 2, line = 1.75)
  
  polygon(c(1:200, 200:1), c(pAvgCI[1,,i], rev(pAvgCI[2,,i])), col = addalpha(completePosterColours[1],.5), border = FALSE)
  lines(1:200,pAveraged[,i], lwd = 4, col = completePosterColours[3])
}

par(pty = "m", mai = c(0,.4,.1,.5))
plot(x = NULL, y = NULL, ann = FALSE, axes = FALSE, ylim = c(0, length(midsTemp)), xlim = c(0,.5))
for (i in 1:length(midsTemp)){
  rect(0,i-1,.5, i, col = theColours[i], border = theColours[i])
}
mtext(sprintf("%.1f",pretty(breaksTemp)), 4, at = seq(0, length(midsTemp), length.out = length(pretty(breaksTemp))), las = 1)
mtext("Signal-to-Noise Ratio", 2, font = 2, line = 1.5, adj = 1, at = length(midsTemp))

par(pty = "m", mai = c(0,.4,.1,.5))
plot(x = NULL, y = NULL, ann = FALSE, axes = FALSE, ylim = c(0, length(midsTemp)), xlim = c(0,.5))
for (i in 1:length(midsTemp)){
  rect(0,i-1,.5, i, col = theColours[i], border = theColours[i])
}
mtext(sprintf("%.1f",pretty(breaksTemp)), 4, at = seq(0, length(midsTemp), length.out = length(pretty(breaksTemp))), las = 1)
mtext("Signal-to-Noise Ratio", 2, font = 2, line = 1.5, adj = 1, at = length(midsTemp))
dev.off()


```


```{r}
png("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Figures/ResponseFunction.png", width = 6, height = 6, res = 300, units = "in", bg = "transparent")
par(pty="s")
xLimit <- range(corCond)
yLimit <- range(pretty(range(pAvgCI[,31,])))
plot(x = NULL, y = NULL, xlim = xLimit,ylim = yLimit, axes = FALSE, ann = FALSE)
abline(h = 1, lwd = 2, col = "gray75", lty = 2)

# stripchart(eAveraged[31,1,], method = "jitter", jitter = .05, vertical = TRUE, pch = 19, at = corCond[1], add = TRUE)
# stripchart(eAveraged[31,5,], method = "jitter", jitter = .05, vertical = TRUE, pch = 19, at = corCond[5], add = TRUE)

lines(corCond, pAveraged[31,1:5], lwd = 3, col = completePosterColours[2])
arrows(corCond, pAvgCI[1,31,1:5],corCond, pAvgCI[2,31,1:5], length = .015, angle = 90, code = 3, col = completePosterColours[2], lwd = 3)
points(corCond, pAveraged[31,1:5], cex = 2.2, pch = 21, bg = completePosterColours[2], col = "white", lwd = 1.5)


lines(corCond, pAveraged[31,6:10], lwd = 3, col = completePosterColours[4])
arrows(corCond, pAvgCI[1,31,6:10],corCond, pAvgCI[2,31,6:10], length = .015, angle = 90, code = 3, col = completePosterColours[4], lwd = 3)
points(corCond, pAveraged[31,6:10], cex = 2.2, pch = 21, bg = completePosterColours[4], col = "white", lwd = 1.5)

axis(1, at = corCond, lwd = 2, tck = -.015, labels = FALSE)
axis(2, at = pretty(yLimit), lwd = 2, tck = -.015, labels = FALSE)
mtext(corCond,1, at = corCond, line = .4)
mtext(sprintf("%.2f",pretty(yLimit)),2, at = pretty(yLimit), line = .4, las = 1)
mtext("Interocular Correlation", 1, font =2, line = 1.5)
mtext("Signal-to-Noise Ratio", 2, font = 2, line =2.25)
legend("topleft", legend = c("Correlated Noise", "Anticorrelated Noise"), bty = "n", pch = 21, pt.bg = completePosterColours[c(2,4)], col = completePosterColours[c(2,4)], lwd = 3, pt.cex = 1.5)
dev.off()
```

```{r}
# boxplot(eAveraged[31,5,])
responders <- eAveraged[31,5,] >= median(eAveraged[31,5,])
```

Violin

```{r}
png("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Figures/violingExp2.png", width = 6.5, height = 8, res = 300, units = "in", bg = "transparent")
par(lwd = 2)
xLimit <- c(-1,9.825)
yLimit <- range(pretty(range(eAveraged[31,,])))
plot(x = NULL, y = NULL, xlim = xLimit,ylim = yLimit, axes = FALSE, ann = FALSE)
abline(h = 1, lwd = 2, col = "gray75", lty = 2)

for (i in 1:length(corCond)){
  ddCor <- density(eAveraged[31,i,])
  ddAnti <- density(eAveraged[31,i+5,])
  ddCor$y <- ddCor$y/max(ddCor$y)
  ddAnti$y <- ddAnti$y/max(ddAnti$y)
  
  polygon(-ddCor$y+((i-1)*2.2)-.025, ddCor$x, col = addalpha(completePosterColours[2],.5), border = NA)
  lines(-ddCor$y+((i-1)*2.2)-.025, ddCor$x, lwd = 2, col = completePosterColours[2])
  polygon(ddAnti$y+((i-1)*2.2)+.025, ddAnti$x, col = addalpha(completePosterColours[4],.5), border = NA)
  lines(ddAnti$y+((i-1)*2.2)+.025, ddAnti$x, lwd = 2, col = completePosterColours[4])
  points(((i-1)*2.2)-.25, median(eAveraged[31,i,]), pch = 19, col = completePosterColours[2], cex = 1.5)
  points(((i-1)*2.2)+.25, median(eAveraged[31,i+5,]), pch = 19, col = completePosterColours[4], cex = 1.5)
  
  axis(2, at = pretty(yLimit), lwd = 2, tck = -.01, labels = FALSE)
  mtext(sprintf("%.2f",pretty(yLimit)), 2, at = pretty(yLimit), line = .4, las = 1)
  mtext("Signal-to-Noise Ratio", 2, font = 2, line = 2.5)
  mtext(bquote(phantom(0) %+-%~.(sprintf("%.2f",corCond[i]))), 1, at = ((i-1)*2.2), line = -2)
  mtext("Interocular Correlation", 1, font = 2, line = 0)
}
legend("topleft",legend = c("Correlated Noise", "Anticorrelated Noise"), bty = "n", fill = addalpha(completePosterColours[c(2,4)],.5), border = completePosterColours[c(2,4)])
dev.off()

```


```{r, fig.width=10, fig.height=4}
xLimit <- c(0,4)
yLimit <- c(0,3)

par(mfrow = c(1,2), mai = c(.3,.3,.1,.1), omi = c(.3,.3,.3,.1))
plot(x = NULL, y = NULL, xlim = xLimit, ylim = yLimit, axes = FALSE, ann = FALSE)
for (i in 1:5){
  dd <- density(avgSNRCondition[channelmapping[electrodeLayout %in% c("OZ","POZ", "O1","O2")],31,i,])
  dd$y <- dd$y/max(dd$y)
  abline(h = ((i/2)-.5), lty = 2, col ="gray75",lwd =1)
  polygon(dd$x, dd$y+((i/2)-.5), col = addalpha(theColours[3],.7), border = NA)
  lines(dd$x, dd$y+((i/2)-.5), col = theColours[3], lwd = 2)
}
axis(1, at = pretty(xLimit), tck = -.015, lwd = 2, labels = FALSE)
axis(2, at = c(0,2,2.5,3), tck = -.015, lwd = 2, labels = FALSE)
mtext(pretty(xLimit), 1, at = pretty(xLimit), line = .4)
mtext("Signal-to-Noise Ratio",1, font = 2, line = 1.5)
mtext(c(0,.5,1), 2, at = c(2,2.5,3), las = 1, line = .4)
mtext("Relative\nProportion", 2, font = 2, at = 2.5, adj=.5, line = 2)
text(3.95, seq(0,2,.5)+.15, sprintf("%.2f",corCond))
text(4.15, 2.65, "Interocular\nCorrelation", font = 2, adj = 1)
mtext("Correlated Noise", 3, font = 2)

plot(x = NULL, y = NULL, xlim = xLimit, ylim = yLimit, axes = FALSE, ann = FALSE)
for (i in 1:5){
  dd <- density(avgSNRCondition[channelmapping[electrodeLayout %in% c("OZ","POZ", "O1","O2")],31,i+5,])
  dd$y <- dd$y/max(dd$y)
  abline(h = ((i/2)-.5), lty = 2, col ="gray75",lwd =1)
  polygon(dd$x, dd$y+((i/2)-.5), col = addalpha(theColours[3],.7), border = NA)
  lines(dd$x, dd$y+((i/2)-.5), col = theColours[3], lwd = 2)
}
axis(1, at = pretty(xLimit), tck = -.015, lwd = 2, labels = FALSE)
axis(2, at = c(0,2,2.5,3), tck = -.015, lwd = 2, labels = FALSE)
mtext(pretty(xLimit), 1, at = pretty(xLimit), line = .4)
mtext("Signal-to-Noise Ratio",1, font = 2, line = 1.5)
# mtext(c(0,.5,1), 2, at = c(2,2.5,3), las = 1, line = .4)
# mtext("Relative\nProportion", 2, font = 2, at = 2.5, adj=.5, line = 2)
text(3.95, seq(0,2,.5)+.15, sprintf("%.2f",corCond))
text(4.15, 2.65, "Interocular\nCorrelation", font = 2, adj = 1)
mtext("Anticorrelated Noise", 3, font = 2)

```

```{r}
theDataDirectory <- "~/Library/CloudStorage/GoogleDrive-brichard21@gmail.com/My Drive/YORK/binocularitynoise/Experiment2data/EEGdata/"
theParticipantsTemp <- list.dirs(theDataDirectory, recursive = FALSE, full.names = FALSE)
theParticipants <- theParticipantsTemp[!c(theParticipantsTemp %in% c("P116","P138"))]
theParticipantIDX <- !(theParticipants %in% c("P136","P149", "P141", "P127", "P122"))

participantsBadStereo <- c("P136","P149", "P141", "P127", "P122")
theParticipants <- theParticipants[!(theParticipants %in% participantsBadStereo)]
```


note P136 is in the EEG data. 

behaviour

```{r}
fitCumGauss <- function(params,X, data){
  mean <- params[1]
  sd <- params[2]
  gamma <- .5 #Guess Rate
  lambda <- params[3] #Lapse Rate
  
  YY <- gamma + (1 - gamma - lambda)*.5*pracma::erfc(-sd*(X-mean)/sqrt(2))
  err <- sum((YY - data)**2)
  return(err)
}

cumGauss <- function(params, X){
  mean <- params[1]
  sd <- params[2]
  gamma <- .5 #Guess Rate
  lambda <- .001 #Lapse Rate
  
  YY <- gamma + (1 - gamma - lambda)*.5*pracma::erfc(-sd*(X-mean)/sqrt(2))
  return(YY)
}

fitLogistic <- function(params,X, data){
  alpha <- params[1]
  beta <- params[2]
  gamma <- .5 #Guess Rate
  lambda <- params[3] #Lapse Rate
  
  YY <- gamma + (1 - gamma - lambda)*(1/(1+exp(-1*(beta)*(X-alpha))))
  err <- sum((YY - data)**2)
  return(err)
}

logistic <- function(params, X){
  alpha <- params[1]
  beta <- params[2]
  gamma <- .5 #Guess Rate
  lambda <- params[3] #Lapse Rate
  
  YY <- gamma + (1 - gamma - lambda)*(1/(1+exp(-1*(beta)*(X-alpha))))
  return(YY)
}

fitWeibull <- function(params, X, data){
  alpha <- params[1]
  beta <- params[2]
  gamma <- .5 #Guess Rate
  lambda <- params[3] #Lapse Rate
  
  YY <- gamma + (1 - gamma - lambda)*(1 - exp(-1*(X/alpha)^beta))
  err <- sum((YY - data)**2)
  return(err)
}

weibull <- function(params, X){
  alpha <- params[1]
  beta <- params[2]
  gamma <- .5 #Guess Rate
  lambda <- params[3] #Lapse Rate
  
  YY <- gamma + (1 - gamma - lambda)*(1 - exp(-1*(X/alpha)^beta))
  return(YY)
}

fitGumbell <- function(params, X, data){
  alpha <- params[1]
  beta <- params[2]
  gamma <- .5 #Guess Rate
  lambda <- params[3] #Lapse Rate
  
  YY <- gamma + (1 - gamma - lambda)*(1-exp(-1*10**(beta*(X-alpha))))
  err <- sum((YY - data)**2)
  return(err)
}

gumBell <- function(params, X){
  alpha <- params[1]
  beta <- params[2]
  gamma <- .5 #Guess Rate
  lambda <- params[3] #Lapse Rate
  
  YY <- gamma + (1 - gamma - lambda)*(1-exp(-1*10**(beta*(X-alpha))))
  return(YY)
}
```

```{r, fig.width = 20}
stereoPath <- "~/Library/CloudStorage/GoogleDrive-brichard21@gmail.com/My Drive/YORK/binocularitynoise/Experiment2data/Results/"
pixperdeg <- 36.7325
threshold.Exp2 <- NULL
nSamples <- 1000

threshold.CI.Exp2 <- matrix(NA, nrow = 1000, ncol = length(theParticipants))
par(mfrow = c(7,7), mai = c(.1,.1,.1,.1))
propCorrectMatrix <- matrix(NA, nrow = , ncol = length(theParticipants))
for (P in 1:length(theParticipants)){
  alltrials <- 0*(1:9)
  allcorrect <- alltrials
  for (block in 1:3){
    data <- R.matlab::readMat(paste0(stereoPath,theParticipants[P], "/", theParticipants[P], "SC_", block, ".mat"))
    alltrials <- alltrials + colSums(data$R[,,1]$ntrials)
    allcorrect <- allcorrect + colSums(data$R[,,1]$ncorrect)
  }
  propcorr <- allcorrect/alltrials
  disparities <- c(0.00375, 0.0075, 0.015, 0.03, 0.06, 0.12, 0.24, 0.48, 0.96)*.5*60
  disparitiesArcSec <- (c(0.00375, 0.0075, 0.015, 0.03, 0.06, 0.12, 0.24, 0.48, 0.96)*.5*60)/2*60
  disparitiesdB <- 20*log10(disparities)
  
  i <- which(alltrials>0)
  disparitiesC <- disparities[i]
  CdB <- disparitiesdB[i]
  Ncorrect <- allcorrect[i]
  Ntrials <- alltrials[i]
  arcsec <- disparitiesArcSec[i]
  datatofit <- data.frame(CdB,Ncorrect,Ntrials, arcsec)
  datatofit$propCorrect <- datatofit$Ncorrect/datatofit$Ntrials
  
  theParams <- c(-3,.5,.001)
  theParamsBest <- optim(theParams,fn = fitGumbell, X = datatofit$CdB, data = datatofit$propCorrect)
  threshold.Exp2[P] <- theParamsBest$par[1]
  
  # sampleData <- data.frame(disp = rep(CdB, Ntrials))
  # for (iii in 1:length(Ntrials)){
  #   sampleData$response[sampleData$disp == CdB[iii]] <- rep(c(0,1),c(Ntrials[iii]-Ncorrect[iii],Ncorrect[iii]))
  # }
  
  # for (ii in 1:1000){
  #   rowIDX <- sample(1:dim(sampleData)[1],dim(sampleData)[1], replace = TRUE)
  #   tempData <- aggregate(response ~ disp, data = sampleData[rowIDX,], FUN = mean)
  #   theParamsBest.CI <- optim(theParams,fn = fitGumbell, X = tempData$disp, data = tempData$response)
  #   threshold.CI.Exp2[ii,P] <- theParamsBest.CI$par[1]
  # }
  
  XX <- seq(min(datatofit$CdB), max(datatofit$CdB), .01)
  YY <- gumBell(theParamsBest$par, XX)
  
  xLimit <- range(pretty(range(datatofit$CdB)))
  yLimit <- c(0.5, 1)
  
  plot(x = NULL, y = NULL, xlim = xLimit,ylim = yLimit, axes = FALSE, ann = FALSE)
  lines(XX, YY, lwd = 4, col = theColours[3])
  points(datatofit$CdB, datatofit$propCorrect, cex = 1.5, pch = 21, bg = theColours[3], col = "white", lwd = 1.5)
  points(threshold.Exp2[P], .5, pch = 25, col = "black", bg = "black", cex = 1.2)
  
  axis(1, at = pretty(xLimit), tck = -0.015, lwd = 2, labels = FALSE)
  axis(2, at = pretty(yLimit), tck = -0.015, lwd = 2, labels = FALSE)
  if (P >= 40){
    mtext(pretty(xLimit), 1, at = pretty(xLimit), line = .4)
    mtext("Total Disparity (arcsec)", 1, font = 2, line = 1.5)
  }
  if (P %% 7 == 1){
    mtext(pretty(yLimit), 2, at = pretty(yLimit), line = .4, las = 1)
    mtext("Proportion Correct", 2, font = 2, line = 2.25)
  }
  legend("bottomright", legend = paste0("P", theParticipants[P]), bty = "n")
  
  
  
  
  datatofit$propCorrect
}
pThreshold.CI.Exp2 <- apply(threshold.CI.Exp2, 2, quantile, c(.025, .975), na.rm = TRUE)
```

```{r}
stereoPath <- "~/Library/CloudStorage/GoogleDrive-brichard21@gmail.com/My Drive/YORK/binocularitynoise/Experiment2data/Results/"
pixperdeg <- 36.7325
# threshold.Exp2 <- NULL
# threshold.CI.Exp2 <- matrix(NA, nrow = nSamples, ncol = length(theParticipants))
datatofit <- data.frame(Participant = NA, disparitydB = NA, Ncorrect = NA, Ntrials = NA, arcsec = NA)

for (P in 1:length(theParticipants)){
  alltrials <- 0*(1:9)
  allcorrect <- alltrials
  for (block in 1:3){
    data <- R.matlab::readMat(paste0(stereoPath,theParticipants[P], "/", theParticipants[P], "SC_", block, ".mat"))
    alltrials <- alltrials + colSums(data$R[,,1]$ntrials)
    allcorrect <- allcorrect + colSums(data$R[,,1]$ncorrect)
  }
  disparities <- (c(0.00375, 0.0075, 0.015, 0.03, 0.06, 0.12, 0.24, 0.48, 0.96)*2)/pixperdeg*60*60
  disparitiesArcSec <- (c(0.00375, 0.0075, 0.015, 0.03, 0.06, 0.12, 0.24, 0.48, 0.96)*.5*60)/2*60
  disparitiesdB <- 20*log10(disparities)
  
  i <- which(alltrials>0)
  disparitiesC <- disparities[i]
  CdB <- disparitiesdB[i]
  Ncorrect <- allcorrect[i]
  Ntrials <- alltrials[i]
  arcsec <- disparitiesArcSec[i]
  # propCorrect <- Ncorrect/Ntrials
  PP <- rep(theParticipants[P], length(Ntrials))
  dataTemp <- data.frame(Participant = PP, disparitydB = CdB, Ncorrect = Ncorrect, Ntrials = Ntrials, arcsec = arcsec)
  datatofit <- rbind(datatofit, dataTemp)
}

datatofit <- na.omit(datatofit)
datatofit$propCorrect <- datatofit$Ncorrect/datatofit$Ntrials

dataForRSAStereo <- datatofit

allPAveraged <- aggregate(propCorrect ~ disparitydB, data= datatofit, FUN = mean)
allPSD <- aggregate(propCorrect ~ disparitydB, data= datatofit, FUN = sd)

theParams <- c(-3,.5,.001)
theParamsBest <- optim(theParams,fn = fitGumbell, X = allPAveraged$disparitydB, data = allPAveraged$propCorrect)
```

```{r}
thresholdAvgCI <- NULL
for (i in 1:1000){
  pIDX <- sample(unique(datatofit$Participant), length(unique(datatofit$Participant)), replace = TRUE)
  allPAveraged <- aggregate(propCorrect ~ disparitydB, data= datatofit, FUN = mean, subset = datatofit$Participant %in% pIDX)
  theParams <- c(-3,.5,.001)
  theParamsBest <- optim(theParams,fn = fitGumbell, X = allPAveraged$disparitydB, data = allPAveraged$propCorrect)
  thresholdAvgCI[i] <- theParamsBest$par[1]
}
thresholdAvgCI.95 <- quantile(thresholdAvgCI, c(.025, .975))
10**(thresholdAvgCI.95/20)/2*60
```



```{r, fig.width=6, fig.height=6}
png("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Figures/avgStereoExp2.png", width = 6, height = 6, res = 300, units = "in", bg = "transparent")
XX <- seq(min(allPAveraged$disparitydB), max(allPAveraged$disparitydB), .01)
YY <- gumBell(theParamsBest$par, XX)

theDisps <- unique(datatofit$disparitydB)

yLim <- c(.5, 1)
xLim <- range(pretty(range(allPAveraged$disparitydB)))
plot(x = NULL, y = NULL, xlim = xLim, ylim = yLim, axes = FALSE, ann = FALSE)
for (i in 1:length(theDisps)){
  stripchart(datatofit[datatofit$disparitydB == theDisps[i], "propCorrect"],  jitter = 1, method = "jitter", add = TRUE, vertical = TRUE, xlim = xLim, at = theDisps[i], pch = 19, col = addalpha(theColours[3],.2))
}

lines(XX,YY, lwd = 4, col = theColours[3])
points(allPAveraged$disparitydB, allPAveraged$propCorrect, cex = 3, bg = theColours[3], pch = 21,col = "white")
points(theParamsBest$par[1], .5, pch = 25, col = "black", bg = "black", cex = 1.2)

axis(1, at = pretty(xLim), tck = -.015, lwd = 2, labels = FALSE)
axis(2, at = pretty(yLim), tck = -.015, lwd = 2, labels = FALSE)
axis(3, at = pretty(xLim), tck = -.015, lwd = 2, labels = FALSE)
mtext(pretty(xLim), 1, at = pretty(xLim), line = .4)
mtext(sprintf("%.1f",pretty(yLim)), 2, at = pretty(yLim), line = .4, las = 1)
mtext(round(10**(pretty(xLim)/20)/2*60),3, at = pretty(xLim), line = .4)
mtext("Disparity (dB)", 1, font = 2, line = 1.5)
mtext("Disparity (arcsec)", 3, font = 2, line = 1.5)

mtext("Proportion Correct",2, font = 2, line = 2.25)
dev.off()

# pretty(10**(xLim/20)/2*60)
```

```{r}
theCorrData <- eAveraged[,1:10,theParticipantIDX]

theDataMatrix <- cbind(t(theCorrData[31,,]),threshold.Exp2)
theCors <- matrix(NA, nrow = 11, ncol = nSamples)
for (i in 1:nSamples){
  IDX <- sample(1:dim(theDataMatrix)[1], dim(theDataMatrix)[1], replace = TRUE)
  theM.CI <- cor(theDataMatrix[IDX,], method = "spearman")
  theCors[,i] <- theM.CI[,11]
}

theCors.CI <- apply(theCors, 1, quantile, c(.025, .975))
```

```{r, fig.width=8, fig.height=7}
# png("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Figures/corMatrixExp2.png", width = 8, height = 7, res = 300, units = "in", bg = "transparent")
theM <- cor(cbind(t(theCorrData[31,,]),threshold.Exp2), method = "spearman")
theM[lower.tri(theM)] <- NA
colnames(theM) <- c(paste0("Correlated Noise", corCond*100),paste0("Anticorrelated Noise", corCond*100), "Stereoacuity")
rownames(theM) <- c(paste0("Correlated Noise", corCond*100),paste0("Anticorrelated Noise", corCond*100), "Stereoacuity")

layout(matrix(c(1,2), nrow = 1, ncol = 2),widths = c(.9,.1), heights = 1)
par(pty = "s", mai = c(0,1.4,1.2,0.1), xpd = TRUE)
theMColours <- colourRampFunction(100)
image(1:11, 1:11, matlab::rot90(theM,3), col = theMColours, zlim = c(-1,1), axes = FALSE, ann = FALSE)
# mtext(c(paste0("Correlated\nNoise ", corCond*100), paste0("Anticorrelated\nNoise ", corCond*100), "Stereoacuity"), 2, at = 11:1, las = 1, font = 2, adj=1, line = 1)
text(1:11-.6,11:1,c(paste0("Correlated\nNoise (r=", corCond, ")"),paste0("Anticorrelated\nNoise (r=", corCond, ")"), "Stereoacuity"), adj = 1, font = 2)
mtext(c(paste0("Correlated\nNoise (r=", corCond, ")"), paste0("Anticorrelated\nNoise (r=", corCond, ")"), "Stereoacuity"), 3, at = 1:11, las = 2, font = 2, line = .4)

par(pty = "m", mai = c(0,0.2,1.2, .3))
plot(x = NULL, y = NULL, xlim = c(0,1), ylim = c(0, length(theMColours)), axes = FALSE, ann = FALSE)
for (i in 1:length(theMColours)){
  rect(0, i-1, 1, i, col = theMColours[i], border = theMColours[i ])
}
mtext(pretty(c(-1,1)), 4, at = seq(0,length(theMColours), length.out = length(pretty(c(-1,1)))), las = 1)
mtext(bquote(bold("Spearman's"~rho)), 2, font = 2, at = length(theMColours), adj = 1)
# dev.off()
```


```{r, fig.width=15}
# png("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Figures/pCorSNRThreshold1.exp2.png", width =7, height = 7, res = 300, units = "in", bg = "transparent")
# par(mfrow = c(2,5), mai = c(.3,.1,.1,.05), omi = c(.3,.5,.1,.1), pty = "s")
yLimit <- range(pretty(range(theElectrodeCI.P)))
xLimit <- c(-20,20) #range(pretty(range(pretty(range(pThreshold.CI.Exp2)))))

theMatrix <- matrix(c(2,4,1,3), nrow = 2, ncol = 2, byrow = TRUE)
layout(theMatrix, widths = c(.9,.1), heights = c(.1,.9))

theColoursPP <- NULL
theColoursPP[responders[theParticipantIDX]] <- theColours[7]
theColoursPP[!responders[theParticipantIDX]] <- theColours[3]

par(mai = c(.2,.2,.2,.2), omi = c(.4,.4,.3,.2))
plot(x = NULL, y = NULL, xlim = xLimit, ylim = yLimit, axes = FALSE, ann = FALSE)
abline(h = 1, lwd = 2, lty = 2, col = theColours[1])
arrows(pThreshold.CI.Exp2[1,], theCorrData[31,5,], pThreshold.CI.Exp2[2,], theCorrData[31,5,], length = .015, angle = 90, code = 3, col = theColoursPP, lwd = 2)
arrows(threshold.Exp2, theElectrodeCI.P[1,5,theParticipantIDX], threshold.Exp2, theElectrodeCI.P[2,5,theParticipantIDX], length = .015, angle = 90, code = 3, col = theColoursPP, lwd = 2)
points(threshold.Exp2, theCorrData[31,5,],bg = theColoursPP, pch = 21, cex = 2, col = "white")

axis(1, at = pretty(xLimit), lwd = 2, tck = -.01, labels = FALSE)
axis(2, at = pretty(yLimit), lwd = 2, tck = -.01, labels = FALSE)
axis(3, at = pretty(xLimit), lwd = 2, tck = -.01, labels = FALSE)
axis(4, at = pretty(yLimit), lwd = 2, tck = -.01, labels = FALSE)
mtext(pretty(xLimit), 1, at = pretty(xLimit), line=.6, las = 1)
mtext("Disparity Threshold (dB)", 1, font = 2, line = 2)


mtext(sprintf("%.1f",pretty(yLimit)),2, at = pretty(yLimit), line = .5, las = 1)
mtext("Signal-to-Noise Ratio", 2, font = 2, line = 2.5)

legend("bottomleft", legend = paste0("Interocular Correlation = ",corCond[5]), bty = "n")
legend("bottomright", 
       legend = bquote(rho~"="~.(round(theM[5,11],3))*", 95% CI ["*.(round(theCors.CI[1,5],3))*","*.(round(theCors.CI[2,5],3))*"]"), 
       bty = "n", cex = 1.2) 

mtext("Correlated Noise", 3, font = 2, line = -2, adj =0, at = -20)

dThreshold <- density(threshold.Exp2)
dThreshold$y <- dThreshold$y/max(dThreshold$y)
par(mai = c(0,0.2,0,0.2))
plot(x = NULL, y = NULL, xlim = xLimit, ylim = c(0,1), axes = FALSE, ann = FALSE)
# axis(1)
polygon(dThreshold$x, dThreshold$y,col = addalpha(theColours[3], .5), border = FALSE)
lines(dThreshold$x, dThreshold$y, lwd = 3, col =theColours[3])

dSNR<- density(theCorrData[31,5,])
dSNR$y <- dSNR$y/max(dSNR$y)
par(mai = c(0.2,0,0.2,0))
plot(x = NULL, y = NULL, ylim = yLimit, xlim = c(0,1), axes = FALSE, ann = FALSE)
polygon(dSNR$y, dSNR$x,col = addalpha(theColours[3], .5), border = FALSE)
lines(dSNR$y, dSNR$x, lwd = 3, col = theColours[3])

# dev.off()
```

```{r}
# png("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Figures/pCorSNRThreshold2.exp2.png", width =7, height = 7, res = 300, units = "in", bg = "transparent")
# par(mfrow = c(2,5), mai = c(.3,.1,.1,.05), omi = c(.3,.5,.1,.1), pty = "s")
yLimit <- range(pretty(range(theElectrodeCI.P)))
xLimit <- c(-20,20) #range(pretty(range(pretty(range(pThreshold.CI.Exp2)))))

theMatrix <- matrix(c(2,4,1,3), nrow = 2, ncol = 2, byrow = TRUE)
layout(theMatrix, widths = c(.9,.1), heights = c(.1,.9))

theColoursPP <- NULL
theColoursPP[responders[theParticipantIDX]] <- theColours[7]
theColoursPP[!responders[theParticipantIDX]] <- theColours[3]

par(mai = c(.2,.2,.2,.2), omi = c(.4,.4,.3,.2))
plot(x = NULL, y = NULL, xlim = xLimit, ylim = yLimit, axes = FALSE, ann = FALSE)
abline(h = 1, lwd = 2, lty = 2, col = theColours[1])
arrows(pThreshold.CI.Exp2[1,], theCorrData[31,10,], pThreshold.CI.Exp2[2,], theCorrData[31,10,], length = .015, angle = 90, code = 3, col = theColoursPP, lwd = 2)
arrows(threshold.Exp2, theElectrodeCI.P[1,10,theParticipantIDX], threshold.Exp2, theElectrodeCI.P[2,10,theParticipantIDX], length = .015, angle = 90, code = 3, col = theColoursPP, lwd = 2)
points(threshold.Exp2, theCorrData[31,10,],bg = theColoursPP, pch = 21, cex = 2, col = "white")

axis(1, at = pretty(xLimit), lwd = 2, tck = -.01, labels = FALSE)
axis(2, at = pretty(yLimit), lwd = 2, tck = -.01, labels = FALSE)
axis(3, at = pretty(xLimit), lwd = 2, tck = -.01, labels = FALSE)
axis(4, at = pretty(yLimit), lwd = 2, tck = -.01, labels = FALSE)
mtext(pretty(xLimit), 1, at = pretty(xLimit), line=.6, las = 1)
mtext("Disparity Threshold (dB)", 1, font = 2, line = 2)


# mtext(sprintf("%.1f",pretty(yLimit)),2, at = pretty(yLimit), line = .5, las = 1)
# mtext("Signal-to-Noise Ratio", 2, font = 2, line = 2.5)
# 
legend("bottomleft", legend = paste0("Interocular Correlation = -",corCond[5]), bty = "n")
legend("bottomright", 
       legend = bquote(rho~"="~.(round(theM[10,11],3))*", 95% CI ["*.(round(theCors.CI[1,10],3))*","*.(round(theCors.CI[2,10],3))*"]"), 
       bty = "n", cex = 1.2) 

mtext("Anticorrelated Noise", 3, font = 2, line = -2, adj =0, at = -20)

dThreshold <- density(threshold.Exp2)
dThreshold$y <- dThreshold$y/max(dThreshold$y)
par(mai = c(0,0.2,0,0.2))
plot(x = NULL, y = NULL, xlim = xLimit, ylim = c(0,1), axes = FALSE, ann = FALSE)
# axis(1)
polygon(dThreshold$x, dThreshold$y,col = addalpha(theColours[3], .5), border = FALSE)
lines(dThreshold$x, dThreshold$y, lwd = 3, col =theColours[3])

dSNR<- density(theCorrData[31,10,])
dSNR$y <- dSNR$y/max(dSNR$y)
par(mai = c(0.2,0,0.2,0))
plot(x = NULL, y = NULL, ylim = yLimit, xlim = c(0,1), axes = FALSE, ann = FALSE)
polygon(dSNR$y, dSNR$x,col = addalpha(theColours[3], .5), border = FALSE)
lines(dSNR$y, dSNR$x, lwd = 3, col = theColours[3])

# dev.off()

```


## RSA

```{r}
allPairwiseComp <- expand.grid(seq(1,length(theParticipantIDX),1)[theParticipantIDX], seq(1,length(theParticipantIDX),1)[theParticipantIDX])

par(pty = "s")
SNRRSACor <- matrix(eAveraged[31, 5, allPairwiseComp[,1]] - eAveraged [31, 5, allPairwiseComp[,2]], nrow = sum(theParticipantIDX), ncol = sum(theParticipantIDX))
theMColours <- colourRampFunction(100)
image(pracma::rot90(SNRRSACor,3), col = theMColours, zlim = range(SNRRSACor), axes = FALSE, ann = FALSE)

par(pty = "s")
SNRRSAAnti <- matrix(eAveraged[31, 10, allPairwiseComp[,1]] - eAveraged [31, 10, allPairwiseComp[,2]], nrow = sum(theParticipantIDX), ncol = sum(theParticipantIDX))
image(pracma::rot90(SNRRSAAnti,3), col = theMColours, zlim = range(SNRRSACor), axes = FALSE, ann = FALSE)

allPairwiseCompStereo <- expand.grid(1:sum(theParticipantIDX), 1:sum(theParticipantIDX))
stereoP <- matrix(threshold.Exp2[allPairwiseCompStereo[,1]]-threshold.Exp2[allPairwiseCompStereo[,2]], nrow = sum(theParticipantIDX), ncol = sum(theParticipantIDX))
par(pty = "s")
image(pracma::rot90(stereoP,3), col = theMColours, zlim = range(stereoP), axes = FALSE, ann = FALSE)
```

```{r}
theParticipants <- theParticipantsTemp[!c(theParticipantsTemp %in% c("P116","P138"))]
rivalParticipants <- theParticipants[theParticipants != "P149"]

stereoPath <- "~/Library/CloudStorage/GoogleDrive-brichard21@gmail.com/My Drive/YORK/binocularitynoise/Experiment2data/"

binocularbalance <- NULL
averageDominanceDuration <- NULL
sdDominanceDuration <- NULL

binocularBalanceCIs <- matrix(NA, nrow = nSamples, ncol = length(rivalParticipants))
dominanceDurationCIs <- matrix(NA, nrow = nSamples, ncol = length(rivalParticipants))

allPsRivalry <- data.frame(participant = rivalParticipants, dominanceDuration = NA, binocularBalance = NA)

for (P in 1:length(rivalParticipants)){
  ndurs <- c(0,0)
  results <- matrix(0,nrow=2,ncol=10000)
  for (block in 1:5){
    data <- readMat(paste(stereoPath,'Results/',rivalParticipants[P],'/',rivalParticipants[P],'rivalry_',block,'.mat',sep=''))
    
    laststate <- 0
    for (t in 1:length(data$R[,,1]$resps)){
      state <- data$R[,,1]$resps[t]
      if (state>0){
        if (state!=laststate){
          if (laststate>0){
            ndurs[laststate] <- ndurs[laststate] + 1
            results[laststate,ndurs[laststate]] <- 60*((t-1) - starttimeindex)
          }
          starttimeindex <- t
          laststate <- state
        }}}
  } 
  binocularbalance[P] <- sum(results[1,1:ndurs[1]])/sum(results[2,1:ndurs[2]])
  averageDominanceDuration[P] <- mean(c(results[1,1:ndurs[1]], results[2,1:ndurs[2]]))
  
  allPsRivalry[allPsRivalry$participant == rivalParticipants[P], "dominanceDuration"] <- averageDominanceDuration[P]
  allPsRivalry[allPsRivalry$participant == rivalParticipants[P], "binocularBalance"] <- binocularbalance[P]
  
  
  for (ii in 1:nSamples){
    IDX1 <- sample(1:ndurs[1], ndurs[1], replace = TRUE)
    IDX2 <- sample(1:ndurs[2], ndurs[2], replace = TRUE)
    
    binocularBalanceCIs[ii,P] <- sum(results[1,IDX1])/sum(results[2,IDX2])
    dominanceDurationCIs[ii,P] <- mean(c(results[1,IDX1], results[2,IDX2]))
  }
  sdDominanceDuration[P] <- sd(results[,1:ndurs[1]])
}

binocularBalanceCI <- apply(binocularBalanceCIs, 2, quantile, c(.025, .975))
dominanceDurationCI <- apply(dominanceDurationCIs, 2, quantile, c(.025, .975))
```

```{r}
mean(allPsRivalry$binocularBalance)
mean(allPsRivalry$dominanceDuration)

bbCI <- NULL
ddCI <- NULL
for (i in 1:1000){
  pIDX <- sample(1:47, 47, replace = TRUE)
  bbCI[i] <- mean(allPsRivalry[pIDX, "binocularBalance"])
  ddCI[i] <- mean(allPsRivalry[pIDX, "dominanceDuration"])
}

quantile(bbCI, c(.025, .975))
quantile(ddCI, c(.025, .975))

```



```{r}
# png("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Figures/DominanceDurationDist.png", width = 5, height = 6, res = 300, units = "in", bg = "transparent")
layout(matrix(c(1,2), nrow = 2, ncol = 1), widths = 1, heights = c(.9,.1))
DD <- density(averageDominanceDuration)
DD$y <- DD$y / max(DD$y)
xLimit <- range(pretty(range(DD$x)))

par(mai = c(0,.2,0,.1), lwd = 3, omi = c(.5,.5,0,0))
plot(x = NULL, y = NULL, xlim = xLimit, ylim = c(0,1), axes = FALSE, ann = FALSE)
polygon(DD$x, DD$y, col = addalpha(theColours[3]), border = NA)
lines(DD$x, DD$y, lwd = 3, col = theColours[3])
axis(2, at = pretty(c(0,1)), lwd = 2, tck = -.01, labels = FALSE)
mtext(pretty(c(0,1)), 2, at = pretty(c(0,1)), line = .4, las = 1)
mtext("Relative Frequency", 2, font = 2, line = 2)
par(mai = c(0,.2,0,.1))
boxplot(averageDominanceDuration, horizontal = TRUE, axes = FALSE, ann = FALSE, ylim = xLimit, border = theColours[3], col = "white")
axis(1, at = pretty(xLimit), tck = -.05, lwd = 2, labels = FALSE)
mtext(pretty(xLimit)/1000, 1, at = pretty(xLimit), line = .4)
mtext("Average Dominance Duration (s)", 1, font = 2, line = 1.5)
# dev.off()
```

```{r}
# png("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Figures/BinocularBanlanceDist.png", width = 5, height = 6, res = 300, units = "in", bg = "transparent")

layout(matrix(c(1,2), nrow = 2, ncol = 1), widths = 1, heights = c(.9,.1))
DD <- density(binocularbalance)
DD$y <- DD$y / max(DD$y)
xLimit <- c(0, max(range(pretty(range(DD$x)))))

par(mai = c(0,.2,0,0), lwd = 3, omi = c(.5,.5,0,0))
plot(x = NULL, y = NULL, xlim = xLimit, ylim = c(0,1), axes = FALSE, ann = FALSE)
polygon(DD$x, DD$y, col = addalpha(theColours[3]), border = NA)
lines(DD$x, DD$y, lwd = 3, col = theColours[3])
axis(2, at = pretty(c(0,1)), lwd = 2, tck = -.01, labels = FALSE)
mtext(pretty(c(0,1)), 2, at = pretty(c(0,1)), line = .4, las = 1)
mtext("Relative Frequency", 2, font = 2, line = 2)
par(mai = c(0,.2,0,.1))
boxplot(binocularbalance, horizontal = TRUE, axes = FALSE, ann = FALSE, ylim = xLimit, border = theColours[3], col = "white")
axis(1, at = pretty(xLimit), tck = -.05, lwd = 2, labels = FALSE)
mtext(pretty(xLimit), 1, at = pretty(xLimit), line = .4)
mtext("Binocular Balance", 1, font = 2, line = 1.5)
# dev.off()
```


```{r, fig.width=10}
theParticipants <- theParticipantsTemp[!c(theParticipantsTemp %in% c("P116","P138"))]
theParticipantsRivalryIDX <- theParticipants != "P149"

theM <- cor(cbind(t(eAveraged[31,1:10,theParticipantsRivalryIDX]),binocularbalance, averageDominanceDuration), method = "spearman")
theM[lower.tri(theM)] <- NA
# png("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Figures/corMatrixExp2_Rivalry.png", width = 8, height = 7, res = 300, units = "in", bg = "transparent")

layout(matrix(c(1,2), nrow = 1, ncol = 2),widths = c(.9,.1), heights = 1)
par(pty = "s", mai = c(0,1.4,1.2,0.1), xpd = TRUE)
image(1:12, 1:12, matlab::rot90(theM,3), col = theMColours, zlim = c(-1,1), axes = FALSE, ann = FALSE)

# mtext(c(paste0("Correlated\nNoise ", corCond*100), paste0("Anticorrelated\nNoise ", corCond*100), "Binocular\nBalance", "Dominance\nDuration"), 2, at = 12:1, las = 1, font = 2, adj=1, line = 1)
text(1:12-.6,12:1,c(paste0("Correlated\nNoise (r=", corCond,")"), paste0("Anticorrelated\nNoise (r=", corCond,")"), "Binocular\nBalance", "Dominance\nDuration"), adj = 1, font = 2)
mtext(c(paste0("Correlated\nNoise (r=", corCond,")"), paste0("Anticorrelated\nNoise (r=", corCond,")"), "Binocular\nBalance", "Dominance\nDuration"), 3, at = 1:12, las = 2, font = 2, line = .4)

par(pty = "m", mai = c(0,0.2,1.2, .3))
plot(x = NULL, y = NULL, xlim = c(0,1), ylim = c(0, length(theMColours)), axes = FALSE, ann = FALSE)
for (i in 1:length(theMColours)){
  rect(0, i-1, 1, i, col = theMColours[i], border = theMColours[i ])
}
mtext(pretty(c(-1,1)), 4, at = seq(0,length(theMColours), length.out = length(pretty(c(-1,1)))), las = 1)
mtext(bquote(bold("Spearman's"~rho)), 2, font = 2, at = length(theMColours), adj = 1)
# dev.off()
```

```{r}
theDataMatrix <- cbind(t(eAveraged[31,1:10,theParticipantsRivalryIDX]),binocularbalance, averageDominanceDuration)
theCorsBalance <- matrix(NA, nrow = 12, ncol = nSamples)
theCorsDuration <- matrix(NA, nrow = 12, ncol = nSamples)
for (i in 1:nSamples){
  IDX <- sample(1:dim(theDataMatrix)[1], dim(theDataMatrix)[1], replace = TRUE)
  theM.CI <- cor(theDataMatrix[IDX,], method = "spearman")
  theCorsBalance[,i] <- theM.CI[,11]
  theCorsDuration[,i] <- theM.CI[,12]
}

theCorsBalance.CI <- apply(theCorsBalance, 1, quantile, c(.025, .975))
theCorsDuration.CI <- apply(theCorsDuration, 1, quantile, c(.025, .975))
```

```{r, fig.width=10}
png("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Figures/corDOminanceDUrationexp2.png", width =7, height = 7, res = 300, units = "in", bg = "transparent")
yLimit <- range(pretty(range(theElectrodeCI.P[,c(5,10),])))
xLimit <- range(pretty(range(pretty(range(dominanceDurationCI)))))

theMatrix <- matrix(c(2,4,1,3), nrow = 2, ncol = 2, byrow = TRUE)
layout(theMatrix, widths = c(.9,.1), heights = c(.1,.9))

par(mai = c(.2,.2,.2,.2), omi = c(.4,.4,.3,.2))
plot(x = NULL, y = NULL, xlim = xLimit, ylim = yLimit, axes = FALSE, ann = FALSE)
abline(h = 1, lwd = 2, lty = 2, col = theColours[1])
arrows(dominanceDurationCI[1,], theDataMatrix[,5], dominanceDurationCI[2,], theDataMatrix[,5], length = .015, angle = 90, code = 3, col = theColours[3], lwd = 2)
arrows(averageDominanceDuration, theElectrodeCI.P[1,5,], averageDominanceDuration, theElectrodeCI.P[2,5,], length = .015, angle = 90, code = 3, col = theColours[3], lwd = 2)
points(averageDominanceDuration, theDataMatrix[,5],bg = theColours[3], pch = 21, cex = 2, col = "white")

axis(1, at = pretty(xLimit), lwd = 2, tck = -.01, labels = FALSE)
axis(2, at = pretty(yLimit), lwd = 2, tck = -.01, labels = FALSE)
axis(3, at = pretty(xLimit), lwd = 2, tck = -.01, labels = FALSE)
axis(4, at = pretty(yLimit), lwd = 2, tck = -.01, labels = FALSE)

mtext(pretty(xLimit)/1000, 1, at = pretty(xLimit), line=.6, las = 1)
mtext("Dominance Duration (s)", 1, font = 2, line = 2)

mtext(sprintf("%.1f",pretty(yLimit)),2, at = pretty(yLimit), line = .5, las = 1)
mtext("Signal-to-Noise Ratio", 2, font = 2, line = 2.75)

legend("bottomleft", paste0("Interocular Correlation = ",corCond[5]),bty = "n")
legend("bottomright", 
       legend = bquote(rho~"="~.(round(theM[5,12],3))*", 95% CI ["*.(round(theCorsDuration.CI[1,5],3))*","*.(round(theCorsDuration.CI[2,5],3))*"]"), 
       bty = "n", cex = 1.2) 

mtext("Correlated Noise", 3, font = 2, line = -2, adj =0, at = 0)

dThreshold <- density(averageDominanceDuration)
dThreshold$y <- dThreshold$y/max(dThreshold$y)
par(mai = c(0,0.2,0,0.2))
plot(x = NULL, y = NULL, xlim = xLimit, ylim = c(0,1), axes = FALSE, ann = FALSE)
# axis(1)
polygon(dThreshold$x, dThreshold$y,col = addalpha(theColours[3], .5), border = FALSE)
lines(dThreshold$x, dThreshold$y, lwd = 3, col =theColours[3])

dSNR<- density(theDataMatrix[,5])
dSNR$y <- dSNR$y/max(dSNR$y)
par(mai = c(0.2,0,0.2,0))
plot(x = NULL, y = NULL, ylim = yLimit, xlim = c(0,1), axes = FALSE, ann = FALSE)
polygon(dSNR$y, dSNR$x,col = addalpha(theColours[3], .5), border = FALSE)
lines(dSNR$y, dSNR$x, lwd = 3, col = theColours[3])

dev.off()
```

```{r}
png("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Figures/anticorDOminanceDUrationexp2.png", width =7, height = 7, res = 300, units = "in", bg = "transparent")
yLimit <- range(pretty(range(theElectrodeCI.P[,c(5,10),])))
xLimit <- range(pretty(range(pretty(range(dominanceDurationCI)))))

theMatrix <- matrix(c(2,4,1,3), nrow = 2, ncol = 2, byrow = TRUE)
layout(theMatrix, widths = c(.9,.1), heights = c(.1,.9))

par(mai = c(.2,.2,.2,.2), omi = c(.4,.4,.3,.2))
plot(x = NULL, y = NULL, xlim = xLimit, ylim = yLimit, axes = FALSE, ann = FALSE)
abline(h = 1, lwd = 2, lty = 2, col = theColours[1])
arrows(dominanceDurationCI[1,], theDataMatrix[,10], dominanceDurationCI[2,], theDataMatrix[,10], length = .015, angle = 90, code = 3, col = theColours[3], lwd = 2)
arrows(averageDominanceDuration, theElectrodeCI.P[1,10,], averageDominanceDuration, theElectrodeCI.P[2,10,], length = .015, angle = 90, code = 3, col = theColours[3], lwd = 2)
points(averageDominanceDuration, theDataMatrix[,10],bg = theColours[3], pch = 21, cex = 2, col = "white")

axis(1, at = pretty(xLimit), lwd = 2, tck = -.01, labels = FALSE)
axis(2, at = pretty(yLimit), lwd = 2, tck = -.01, labels = FALSE)
axis(3, at = pretty(xLimit), lwd = 2, tck = -.01, labels = FALSE)
axis(4, at = pretty(yLimit), lwd = 2, tck = -.01, labels = FALSE)

mtext(pretty(xLimit)/1000, 1, at = pretty(xLimit), line=.6, las = 1)
mtext("Dominance Duration (s)", 1, font = 2, line = 2)

# mtext(sprintf("%.1f",pretty(yLimit)),2, at = pretty(yLimit), line = .5, las = 1)
# mtext("Signal-to-Noise Ratio", 2, font = 2, line = 2.75)

legend("bottomleft", paste0("Interocular Correlation = -",corCond[5]),bty = "n")
legend("bottomright", 
       legend = bquote(rho~"="~.(round(theM[10,12],3))*", 95% CI ["*.(round(theCorsDuration.CI[1,10],3))*","*.(round(theCorsDuration.CI[2,10],3))*"]"), 
       bty = "n", cex = 1.2) 

mtext("Anticorrelated Noise", 3, font = 2, line = -2, adj =0, at = 0)

dThreshold <- density(averageDominanceDuration)
dThreshold$y <- dThreshold$y/max(dThreshold$y)
par(mai = c(0,0.2,0,0.2))
plot(x = NULL, y = NULL, xlim = xLimit, ylim = c(0,1), axes = FALSE, ann = FALSE)
# axis(1)
polygon(dThreshold$x, dThreshold$y,col = addalpha(theColours[3], .5), border = FALSE)
lines(dThreshold$x, dThreshold$y, lwd = 3, col =theColours[3])

dSNR<- density(theDataMatrix[,10])
dSNR$y <- dSNR$y/max(dSNR$y)
par(mai = c(0.2,0,0.2,0))
plot(x = NULL, y = NULL, ylim = yLimit, xlim = c(0,1), axes = FALSE, ann = FALSE)
polygon(dSNR$y, dSNR$x,col = addalpha(theColours[3], .5), border = FALSE)
lines(dSNR$y, dSNR$x, lwd = 3, col = theColours[3])

dev.off()
```

```{r}
png("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Figures/corBalanceexp2.png", width =7, height = 7, res = 300, units = "in", bg = "transparent")
yLimit <- range(pretty(range(theElectrodeCI.P[,c(5,10),])))
# xLimit <- range(pretty(range(pretty(range(binocularBalanceCI)))))
xLimit <- c(0,6)

theMatrix <- matrix(c(2,4,1,3), nrow = 2, ncol = 2, byrow = TRUE)
layout(theMatrix, widths = c(.9,.1), heights = c(.1,.9))

par(mai = c(.2,.2,.2,.2), omi = c(.4,.4,.3,.2))
plot(x = NULL, y = NULL, xlim = xLimit, ylim = yLimit, axes = FALSE, ann = FALSE)
abline(h = 1, lwd = 2, lty = 2, col = theColours[1])
arrows(binocularBalanceCI[1,], theDataMatrix[,5], binocularBalanceCI[2,], theDataMatrix[,5], length = .015, angle = 90, code = 3, col = theColours[3], lwd = 2)
arrows(binocularbalance, theElectrodeCI.P[1,5,], binocularbalance, theElectrodeCI.P[2,5,], length = .015, angle = 90, code = 3, col = theColours[3], lwd = 2)
points(binocularbalance, theDataMatrix[,5],bg = theColours[3], pch = 21, cex = 2, col = "white")

axis(1, at = pretty(xLimit), lwd = 2, tck = -.01, labels = FALSE)
axis(2, at = pretty(yLimit), lwd = 2, tck = -.01, labels = FALSE)
axis(3, at = pretty(xLimit), lwd = 2, tck = -.01, labels = FALSE)
axis(4, at = pretty(yLimit), lwd = 2, tck = -.01, labels = FALSE)

mtext(pretty(xLimit), 1, at = pretty(xLimit), line=.6, las = 1)
mtext("Binocular Balance", 1, font = 2, line = 2)

mtext(sprintf("%.1f",pretty(yLimit)),2, at = pretty(yLimit), line = .5, las = 1)
mtext("Signal-to-Noise Ratio", 2, font = 2, line = 2.75)

legend("bottomleft", paste0("Interocular Correlation = ",corCond[5]),bty = "n")
legend("bottomright", 
       legend = bquote(rho~"="~.(round(theM[5,11],3))*", 95% CI ["*.(round(theCorsDuration.CI[1,5],3))*","*.(round(theCorsDuration.CI[2,5],3))*"]"), 
       bty = "n", cex = 1.2) 

mtext("Anticorrelated Noise", 3, font = 2, line = -2, adj =0, at = 0)

dThreshold <- density(binocularbalance)
dThreshold$y <- dThreshold$y/max(dThreshold$y)
par(mai = c(0,0.2,0,0.2))
plot(x = NULL, y = NULL, xlim = xLimit, ylim = c(0,1), axes = FALSE, ann = FALSE)
# axis(1)
polygon(dThreshold$x, dThreshold$y,col = addalpha(theColours[3], .5), border = FALSE)
lines(dThreshold$x, dThreshold$y, lwd = 3, col =theColours[3])

dSNR<- density(theDataMatrix[,5])
dSNR$y <- dSNR$y/max(dSNR$y)
par(mai = c(0.2,0,0.2,0))
plot(x = NULL, y = NULL, ylim = yLimit, xlim = c(0,1), axes = FALSE, ann = FALSE)
polygon(dSNR$y, dSNR$x,col = addalpha(theColours[3], .5), border = FALSE)
lines(dSNR$y, dSNR$x, lwd = 3, col = theColours[3])

dev.off()
```


```{r}
png("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Figures/anticorBalanceexp2.png", width =7, height = 7, res = 300, units = "in", bg = "transparent")
yLimit <- range(pretty(range(theElectrodeCI.P[,c(5,10),])))
# xLimit <- range(pretty(range(pretty(range(binocularBalanceCI)))))
xLimit <- c(0,6)

theMatrix <- matrix(c(2,4,1,3), nrow = 2, ncol = 2, byrow = TRUE)
layout(theMatrix, widths = c(.9,.1), heights = c(.1,.9))

par(mai = c(.2,.2,.2,.2), omi = c(.4,.4,.3,.2))
plot(x = NULL, y = NULL, xlim = xLimit, ylim = yLimit, axes = FALSE, ann = FALSE)
abline(h = 1, lwd = 2, lty = 2, col = theColours[1])
arrows(binocularBalanceCI[1,], theDataMatrix[,10], binocularBalanceCI[2,], theDataMatrix[,10], length = .015, angle = 90, code = 3, col = theColours[3], lwd = 2)
arrows(binocularbalance, theElectrodeCI.P[1,10,], binocularbalance, theElectrodeCI.P[2,10,], length = .015, angle = 90, code = 3, col = theColours[3], lwd = 2)
points(binocularbalance, theDataMatrix[,10],bg = theColours[3], pch = 21, cex = 2, col = "white")

axis(1, at = pretty(xLimit), lwd = 2, tck = -.01, labels = FALSE)
axis(2, at = pretty(yLimit), lwd = 2, tck = -.01, labels = FALSE)
axis(3, at = pretty(xLimit), lwd = 2, tck = -.01, labels = FALSE)
axis(4, at = pretty(yLimit), lwd = 2, tck = -.01, labels = FALSE)

mtext(pretty(xLimit), 1, at = pretty(xLimit), line=.6, las = 1)
mtext("Binocular Balance", 1, font = 2, line = 2)

# mtext(sprintf("%.1f",pretty(yLimit)),2, at = pretty(yLimit), line = .5, las = 1)
# mtext("Signal-to-Noise Ratio", 2, font = 2, line = 2.75)

legend("bottomleft", paste0("Interocular Correlation = -",corCond[5]),bty = "n")
legend("bottomright", 
       legend = bquote(rho~"="~.(round(theM[10,11],3))*", 95% CI ["*.(round(theCorsDuration.CI[1,10],3))*","*.(round(theCorsDuration.CI[2,10],3))*"]"), 
       bty = "n", cex = 1.2) 

mtext("Anticorrelated Noise", 3, font = 2, line = -2, adj =0, at = 0)

dThreshold <- density(binocularbalance)
dThreshold$y <- dThreshold$y/max(dThreshold$y)
par(mai = c(0,0.2,0,0.2))
plot(x = NULL, y = NULL, xlim = xLimit, ylim = c(0,1), axes = FALSE, ann = FALSE)
# axis(1)
polygon(dThreshold$x, dThreshold$y,col = addalpha(theColours[3], .5), border = FALSE)
lines(dThreshold$x, dThreshold$y, lwd = 3, col =theColours[3])

dSNR<- density(theDataMatrix[,10])
dSNR$y <- dSNR$y/max(dSNR$y)
par(mai = c(0.2,0,0.2,0))
plot(x = NULL, y = NULL, ylim = yLimit, xlim = c(0,1), axes = FALSE, ann = FALSE)
polygon(dSNR$y, dSNR$x,col = addalpha(theColours[3], .5), border = FALSE)
lines(dSNR$y, dSNR$x, lwd = 3, col = theColours[3])

dev.off()
```

RSA ALL

```{r}

stereoParticipantsIDX <- seq(1,length(theParticipantIDX),1)[theParticipantIDX]
rivarlryParticipantsIDX <- seq(1,length(theParticipantsRivalryIDX),1)[theParticipantsRivalryIDX]

allPairwiseCompSNRStereo <- expand.grid(stereoParticipantsIDX, stereoParticipantsIDX)
allPairwiseCompSNRRivalry <- expand.grid(rivarlryParticipantsIDX, rivarlryParticipantsIDX)

allPairwiseCompStereo <- expand.grid(1:sum(theParticipantIDX), 1:sum(theParticipantIDX))
stereoP <- matrix(threshold.Exp2[allPairwiseCompStereo[,1]]-threshold.Exp2[allPairwiseCompStereo[,2]], nrow = sum(theParticipantIDX), ncol = sum(theParticipantIDX))

lowerIDXStereo <- lower.tri(stereoP)

allPairwiseCompRivalry <- expand.grid(1:sum(theParticipantsRivalryIDX), 1:sum(theParticipantsRivalryIDX))
dominanceDurationRSA <- matrix(averageDominanceDuration[allPairwiseCompRivalry[,1]]-averageDominanceDuration[allPairwiseCompRivalry[,2]], nrow = sum(theParticipantsRivalryIDX), ncol = sum(theParticipantsRivalryIDX))
binocularBalanceRSA <- matrix(binocularbalance[allPairwiseCompRivalry[,1]]-binocularbalance[allPairwiseCompRivalry[,2]], nrow = sum(theParticipantsRivalryIDX), ncol = sum(theParticipantsRivalryIDX))

lowerIDXRivalry <- lower.tri(binocularBalanceRSA)

RSA <- matrix(NA, nrow = 3, ncol = 10)
for (i in 1:10){
  SNRRSAStereo <- matrix(eAveraged[31, i, allPairwiseCompSNRStereo[,1]] - eAveraged [31, i, allPairwiseCompSNRStereo[,2]], nrow = sum(theParticipantIDX), ncol = sum(theParticipantIDX))
  
  SNRRSARivalry<- matrix(eAveraged[31, i, allPairwiseCompSNRRivalry[,1]] - eAveraged [31, i, allPairwiseCompSNRRivalry[,2]], nrow = sum(theParticipantsRivalryIDX), ncol = sum(theParticipantsRivalryIDX))
  
  RSA[1,i] <- cor(SNRRSAStereo[lowerIDXStereo],stereoP[lowerIDXStereo], method = "spearman")
  RSA[2,i] <- cor(SNRRSARivalry[lowerIDXStereo],dominanceDurationRSA[lowerIDXStereo], method = "spearman")
  RSA[3,i] <- cor(SNRRSARivalry[lowerIDXStereo],binocularBalanceRSA[lowerIDXStereo], method = "spearman")
  
}

RSA
```

```{r}
stereoParticipantsIDX <- seq(1,length(theParticipantIDX),1)[theParticipantIDX]
rivarlryParticipantsIDX <- seq(1,length(theParticipantsRivalryIDX),1)[theParticipantsRivalryIDX]
RSA <- array(NA,dim = c(3,10,1000))
for (ii in 1:1000){
  stereoParticipantsSampled <- sample(stereoParticipantsIDX, length(stereoParticipantsIDX), replace = TRUE)
  rivalryParticipantsSampled <- sample(rivarlryParticipantsIDX, length(rivarlryParticipantsIDX), replace = TRUE)
  
  allPairwiseCompSNRStereo <- expand.grid(stereoParticipantsSampled, stereoParticipantsSampled)
  allPairwiseCompSNRRivalry <- expand.grid(rivalryParticipantsSampled, rivalryParticipantsSampled)
  
  allPairwiseCompStereo <- expand.grid(1:sum(theParticipantIDX), 1:sum(theParticipantIDX))
  stereoP <- matrix(threshold.Exp2[allPairwiseCompStereo[,1]]-threshold.Exp2[allPairwiseCompStereo[,2]], nrow = sum(theParticipantIDX), ncol = sum(theParticipantIDX))
  
  lowerIDXStereo <- lower.tri(stereoP)
  
  allPairwiseCompRivalry <- expand.grid(1:sum(theParticipantsRivalryIDX), 1:sum(theParticipantsRivalryIDX))
  dominanceDurationRSA <- matrix(averageDominanceDuration[allPairwiseCompRivalry[,1]]-averageDominanceDuration[allPairwiseCompRivalry[,2]], nrow = sum(theParticipantsRivalryIDX), ncol = sum(theParticipantsRivalryIDX))
  binocularBalanceRSA <- matrix(binocularbalance[allPairwiseCompRivalry[,1]]-binocularbalance[allPairwiseCompRivalry[,2]], nrow = sum(theParticipantsRivalryIDX), ncol = sum(theParticipantsRivalryIDX))
  
  lowerIDXRivalry <- lower.tri(binocularBalanceRSA)
  
  
  for (i in 1:10){
    SNRRSAStereo <- matrix(eAveraged[31, i, allPairwiseCompSNRStereo[,1]] - eAveraged [31, i, allPairwiseCompSNRStereo[,2]], nrow = sum(theParticipantIDX), ncol = sum(theParticipantIDX))
    
    SNRRSARivalry<- matrix(eAveraged[31, i, allPairwiseCompSNRRivalry[,1]] - eAveraged [31, i, allPairwiseCompSNRRivalry[,2]], nrow = sum(theParticipantsRivalryIDX), ncol = sum(theParticipantsRivalryIDX))
    
    RSA[1,i,ii] <- cor(SNRRSAStereo[lowerIDXStereo],stereoP[lowerIDXStereo], method = "spearman")
    RSA[2,i,ii] <- cor(SNRRSARivalry[lowerIDXStereo],dominanceDurationRSA[lowerIDXStereo], method = "spearman")
    RSA[3,i,ii] <- cor(SNRRSARivalry[lowerIDXStereo],binocularBalanceRSA[lowerIDXStereo], method = "spearman")
    
  }
}

apply(RSA, c(1,2), quantile, c(0.025, .975))
```

RSA with correlations instead of distance

```{r}
stereoParticipantsIDX <- seq(1,length(theParticipantIDX),1)[theParticipantIDX]
rivarlryParticipantsIDX <- seq(1,length(theParticipantsRivalryIDX),1)[theParticipantsRivalryIDX]

allPairwiseCompSNRStereo <- expand.grid(stereoParticipantsIDX, stereoParticipantsIDX)
allPairwiseCompSNRRivalry <- expand.grid(rivarlryParticipantsIDX, rivarlryParticipantsIDX)
```

```{r, fig.width = 20}
RSASNR_Cor <- cor(eAveraged[31, 1:5,stereoParticipantsIDX])
RSASNR_Anti <- cor(eAveraged[31, 6:10,stereoParticipantsIDX])

par(pty = "s")
image(1:length(stereoParticipantsIDX), 1:length(stereoParticipantsIDX), pracma::rot90(RSASNR_Cor),col = theMColours, zlim = range(-1,1),axes = FALSE, ann = FALSE)
mtext(stereoParticipantsIDX,3,at= 1:length(stereoParticipantsIDX))
mtext(stereoParticipantsIDX,4,at= rev(1:length(stereoParticipantsIDX)), las = 2)

par(pty = "s")
theOrder <- order(eAveraged[31, 5,stereoParticipantsIDX])
image(1:length(stereoParticipantsIDX), 1:length(stereoParticipantsIDX), pracma::rot90(RSASNR_Cor[theOrder,theOrder]),col = theMColours, zlim = range(-1,1),axes = FALSE, ann = FALSE)
mtext(stereoParticipantsIDX[theOrder],3,at= 1:length(stereoParticipantsIDX))
mtext(stereoParticipantsIDX[theOrder],4,at= rev(1:length(stereoParticipantsIDX)), las = 2)

# par(pty = "s")
# image(pracma::rot90(RSASNR_Anti),col = theMColours, zlim = range(-1,1),axes = FALSE, ann = FALSE)
```

```{r, fig.width = 10}
theFirstPs <- which(stereoParticipantsIDX %in% c(1,2,4,29,30,31,33,35,37,38,39,40))
theOtherPs <- which(stereoParticipantsIDX %in% c(23,10,8,9,5,11,16,12))

yLimit <- range(pretty(range(theElectrodeCI.P)))
xLimit <- c(-20,20) #range(pretty(range(pretty(range(pThreshold.CI.Exp2)))))

theMatrix <- matrix(c(2,4,1,3), nrow = 2, ncol = 2, byrow = TRUE)
layout(theMatrix, widths = c(.9,.1), heights = c(.1,.9))

theColoursPP <- rep("gray75", sum(theParticipantIDX))
theColoursPP[theFirstPs] <- theColours[7]
theColoursPP[theOtherPs] <- theColours[3]

# theColoursPP[responders[theParticipantIDX]] <- theColours[7]
# theColoursPP[!responders[theParticipantIDX]] <- theColours[3]

par(mai = c(.2,.2,.2,.2), omi = c(.4,.4,.3,.2))
plot(x = NULL, y = NULL, xlim = xLimit, ylim = yLimit, axes = FALSE, ann = FALSE)
abline(h = 1, lwd = 2, lty = 2, col = theColours[1])
arrows(pThreshold.CI.Exp2[1,], theCorrData[31,5,], pThreshold.CI.Exp2[2,], theCorrData[31,5,], length = .015, angle = 90, code = 3, col = theColoursPP, lwd = 2)
arrows(threshold.Exp2, theElectrodeCI.P[1,5,theParticipantIDX], threshold.Exp2, theElectrodeCI.P[2,5,theParticipantIDX], length = .015, angle = 90, code = 3, col = theColoursPP, lwd = 2)
points(threshold.Exp2, theCorrData[31,5,],bg = theColoursPP, pch = 21, cex = 2, col = "white")

axis(1, at = pretty(xLimit), lwd = 2, tck = -.01, labels = FALSE)
axis(2, at = pretty(yLimit), lwd = 2, tck = -.01, labels = FALSE)
axis(3, at = pretty(xLimit), lwd = 2, tck = -.01, labels = FALSE)
axis(4, at = pretty(yLimit), lwd = 2, tck = -.01, labels = FALSE)
mtext(pretty(xLimit), 1, at = pretty(xLimit), line=.6, las = 1)
mtext("Disparity Threshold (dB)", 1, font = 2, line = 2)


mtext(sprintf("%.1f",pretty(yLimit)),2, at = pretty(yLimit), line = .5, las = 1)
mtext("Signal-to-Noise Ratio", 2, font = 2, line = 2.5)

legend("bottomleft", legend = paste0("Interocular Correlation = ",corCond[5]), bty = "n")
legend("bottomright", 
       legend = bquote(rho~"="~.(round(theM[5,11],3))*", 95% CI ["*.(round(theCors.CI[1,5],3))*","*.(round(theCors.CI[2,5],3))*"]"), 
       bty = "n", cex = 1.2) 

mtext("Correlated Noise", 3, font = 2, line = -2, adj =0, at = -20)

dThreshold <- density(threshold.Exp2)
dThreshold$y <- dThreshold$y/max(dThreshold$y)
par(mai = c(0,0.2,0,0.2))
plot(x = NULL, y = NULL, xlim = xLimit, ylim = c(0,1), axes = FALSE, ann = FALSE)
# axis(1)
polygon(dThreshold$x, dThreshold$y,col = addalpha(theColours[3], .5), border = FALSE)
lines(dThreshold$x, dThreshold$y, lwd = 3, col =theColours[3])

dSNR<- density(theCorrData[31,5,])
dSNR$y <- dSNR$y/max(dSNR$y)
par(mai = c(0.2,0,0.2,0))
plot(x = NULL, y = NULL, ylim = yLimit, xlim = c(0,1), axes = FALSE, ann = FALSE)
polygon(dSNR$y, dSNR$x,col = addalpha(theColours[3], .5), border = FALSE)
lines(dSNR$y, dSNR$x, lwd = 3, col = theColours[3])
```













```{r}
thePs <- unique(dataForRSAStereo$Participant)
thedBs <- unique(dataForRSAStereo$disparitydB)
theWideRSAStereoData <- matrix(NA, nrow = length(thedBs), ncol = sum(theParticipantIDX))

for (P in 1:sum(theParticipantIDX)){
  for (d in 1:length(thedBs)){
    theValue <- dataForRSAStereo[dataForRSAStereo$Participant == thePs[P] & dataForRSAStereo$disparitydB == thedBs[d], "propCorrect"]
    if (length(theValue) > 0){
      theWideRSAStereoData[d,P] <- theValue
    }
  }
}

stereoRSA <- cor(theWideRSAStereoData, use = "complete.obs", method = "spearman")

par(pty = "s")
image(pracma::rot90(stereoRSA),col = theMColours, zlim = range(-1,1),axes = FALSE, ann = FALSE)

par(pty = "s")
image(pracma::rot90(stereoP,3), col = theMColours, zlim = range(stereoP), axes = FALSE, ann = FALSE)
```

```{r}
theLowerTriag <- lower.tri(RSASNR_Cor)
RSAEEGStereo_Cor <- cor(RSASNR_Cor[theLowerTriag], stereoRSA[theLowerTriag], method = "spearman")
RSAEEGStereo_Anti <- cor(RSASNR_Anti[theLowerTriag], stereoRSA[theLowerTriag], method = "spearman")
```


```{r}
library(igraph)
```
```{r}
igraph::g
```

