---
title: "Untitled"
output: html_document
date: "2026-05-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Stimuli
"C:\Users\Bruno\Box\Manuscripts\Binocular Noise Study\Figures"

```{r}
theNoiseIMs <- R.matlab::readMat("C:/Users/Bruno/Box/Manuscripts/Binocular Noise Study/Figures/noiseImages.mat")
```

```{r}
#png("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Figures/interocularCorrelation.png", width = 6, height = 5, res = 300, units = "in",bg = "transparent")
par(mfcol = c(2,1), mai = c(.2,.1,.2,.1), omi = c(.4,.6,0,0))
xLimit = c(0,1)
yLimit = c(0,1)

theSine <- (-cos(2*pi*3*seq(0,1,length.out = 120))+1)/2
plot(x = NULL, y = NULL, xlim = xLimit, ylim = yLimit, axes = FALSE, ann = FALSE)
lines(seq(0,1,length.out = 120),theSine, lwd = 2, lty = 2, col = "gray75")
lines(seq(0,1,length.out = 120), rep(theNoiseIMs$noiseIMs[,,1]$ImageCorrelation,3), col = theColours[3], lwd = 3)

axis(1, at = pretty(c(0,1)), tck = -0.015, lwd = 2, labels = FALSE)
axis(2, at = pretty(yLimit), tck = -0.015, lwd = 2, labels = FALSE)
# mtext(pretty(c(0,1))*1000, 1, at = pretty(c(0,1)), line = .4)
mtext(sprintf("%.1f",pretty(yLimit)), 2, at = pretty(yLimit), line = .4, las = 1)
# mtext("Time (ms)", 1, line = 1.5, font = 2)
mtext("Interocular Correlation", 2, font = 2, line = 2.5)
mtext("Correlated Noise", 3, font = 2, adj = 0, at = 0, line = 0)

yLimit = c(-1,0)
theSine <- -(-cos(2*pi*3*seq(0,1,length.out = 120))+1)/2
plot(x = NULL, y = NULL, xlim = xLimit, ylim = yLimit, axes = FALSE, ann = FALSE)
lines(seq(0,1,length.out = 120),theSine, lwd = 2, lty = 2, col = "gray75")
lines(seq(0,1,length.out = 120), rep(theNoiseIMs$noiseIMs[,,2]$ImageCorrelation,3), col = theColours[4], lwd = 3)

axis(1, at = pretty(c(0,1)), tck = -0.015, lwd = 2, labels = FALSE)
axis(2, at = pretty(yLimit), tck = -0.015, lwd = 2, labels = FALSE)
mtext(pretty(c(0,1))*1000, 1, at = pretty(c(0,1)), line = .4)
mtext(sprintf("%.1f",pretty(yLimit)), 2, at = pretty(yLimit), line = .4, las = 1)
mtext("Time (ms)", 1, line = 1.5, font = 2)
mtext("Interocular Correlation", 2, font = 2, line = 2.5)
mtext("Anticorrelated Noise", 3, font = 2, adj = 0, at = 0, line = 0)
#dev.off()
```

```{r}
theNoiseIMs$noiseIMs[,,1]$IM1[,,i]
```


```{r}
for (i in 1:dim(theNoiseIMs$noiseIMs[,,1]$IM1)[3]){
 # png(paste0("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Figures/exampleStimuli/interocularCor_",round(theNoiseIMs$noiseIMs[,,1]$ImageCorrelation[i],3),".png"), width = 8, height = 4, res = 300, units = "in", bg = "transparent")
  
  im1 <- theNoiseIMs$noiseIMs[,,1]$IM1[,,i]
  im2 <- theNoiseIMs$noiseIMs[,,1]$IM2[,,i]
  im1[im1 > 1] <- 1
  im2[im2 > 1] <- 1
  im1[im1 < 0] <- 0
  im2[im2 < 0] <- 0
  par(mfcol = c(1,2), pty = "s", mai = c(0,0.05,0,0), omi = c(0,0,0,0))
  grayColours <- gray.colors(256, start = 0, end = 1, gamma = 2)
  image(im1, col = grayColours, zlim = c(0,1), axes = FALSE, ann = FALSE)
  text(0,.97, "Left Eye", font = 2, col = "white", adj = 0)
  image(im2, col = grayColours, zlim = c(0,1), axes = FALSE, ann = FALSE)
  text(1,.97, "Right Eye", font = 2, col = "white", adj = 1)
  #dev.off()
}

for (i in 1:dim(theNoiseIMs$noiseIMs[,,1]$IM1)[3]){
  png(paste0("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Figures/exampleStimuli/NEGinterocularCor_",round(theNoiseIMs$noiseIMs[,,1]$ImageCorrelation[i],3),".png"), width = 8, height = 4, res = 300, units = "in", bg = "transparent")
  
  im1 <- theNoiseIMs$noiseIMs[,,2]$IM1[,,i]
  im2 <- theNoiseIMs$noiseIMs[,,2]$IM2[,,i]
  im1[im1 > 1] <- 1
  im2[im2 > 1] <- 1
  im1[im1 < 0] <- 0
  im2[im2 < 0] <- 0
  par(mfcol = c(1,2), pty = "s", mai = c(0,0.05,0,0), omi = c(0,0,0,0))
  grayColours <- gray.colors(256, start = 0, end = 1, gamma = 1)
  image(im1, col = grayColours, zlim = c(0,1), axes = FALSE, ann = FALSE)
  text(0,.97, "Left Eye", font = 2, col = "white", adj = 0)
  image(im2, col = grayColours, zlim = c(0,1), axes = FALSE, ann = FALSE)
  text(1,.97, "Right Eye", font = 2, col = "white", adj = 1)
  dev.off()
}
```


# Sinusoidal Gratings

comp = grating.*E.contrastlist;
comp = (1+comp)/2;
comp = doimagegamma(comp);
gratingtexture = Screen('MakeTexture', w, comp, [], [], 2);

comp = grating.*0;
comp = (1+comp)/2;



u = f .* cos(o) * 2 * pi;
v = f .* sin(o) * 2 * pi;

imag1 = zeros(Regionsize, Regionsize);
[xx, yy] = meshgrid(1:Regionsize, 1:Regionsize);

imag1(:,:) = (c .* sin(u .*(xx-x0) + v.*(yy-y0) + p));


```{r}
mkGrating <- function(Regionsize, f, o, p, c){
  p <- p*pi/180
  o <- o*2*pi/360		
  f <- f/Regionsize
  x0 <- ((Regionsize+1)/2)
  y0 <- x0
  
  u <- f * cos(o) * 2 * pi
  v <- f * sin(o) * 2 * pi
  
  xx <- pracma::meshgrid(1:Regionsize, 1:Regionsize);
  
  imag1 <- (c * sin(u *(xx$X-x0) + v*(xx$Y-y0) + p))
  return(imag1)
}
```


```{r}
E.contrastlist <- 48/100

ST.gratingsize <- 36*5
ST.npixelsperdegree <- 36
ST.SF <- 1
ST.ncycles <- ST.SF*ST.gratingsize/ST.npixelsperdegree

grating <- mkGrating(ST.gratingsize, ST.ncycles, 90, 0, 1)
comp = grating*E.contrastlist
comp = (1+comp)/2
png("~/Library/CloudStorage/Box-Box/Manuscripts/Binocular Noise Study/Figures/grating.png", width = 6, height = 6, res = 300, units = "in", bg = "transparent")
par(pty = "s", mai = c(0,0,0,0), omi = c(0,0,0,0))
image(comp, col = gray.colors(256, start = 0, end = 1, gamma = 1), zlim = c(0,1), axes = FALSE, ann = FALSE)
dev.off()
```

